#+TITLE: 浦东新区第十八届明日科技之星
:PROPERTIES:
#+SEQ_TODO: TODO(t) INPROGRESS(p) | DONE(d) ABORT(a@/!)
#+TAGS:
#+STARTUP: logdrawer
#+STARTUP: content
#+STARTUP: hidestars
#+STARTUP: indent
#+CATEGORY: 牛牛
:END:

* 信息收集
:PROPERTIES:
:ID:       5A6182FC-1CA5-4F25-8237-D39F8C00E93F
:END:
- 网站: http://ys.shsunshine.org/kjzx/
- 成果: 
  1. 科学研究论文
  2. 发明创造作品

* 进度安排 [0/0]
:PROPERTIES:
:ID:       94D9C407-7170-452C-AC0B-A5E366C0BABB
:END:
** [1/2] 学生网上申报 (2019年12月25日 ~ 2020年1月30日)
:PROPERTIES:
:ID:       97C5EC62-EB0E-40B7-AF3F-D8A3D8982634
:END:
*** ABORT 经学校审核通过
:PROPERTIES:
:ID:       CA28E005-A726-40AD-98B2-4A89F9994750
:END:
:LOGBOOK:
- State "ABORT"      from "TODO"       [2020-01-20 Mon 14:29] \\
  和张老师沟通，没有这个阶段，可以直接网上填报
:END:
*** TODO 网上填写《学校推荐表》
DEADLINE: <2020-01-23 Thu>
:PROPERTIES:
:ID:       B0DD917A-BA66-4409-81D2-1C792ECBF8B7
:END:


* 收件箱
:PROPERTIES:
:ID:       886F71D5-00C3-45A7-8377-A9BA83345B42
:END:

* 参赛要求
:PROPERTIES:
:ID:       FDD17168-C093-4C50-8116-1F3AD45B090C
:END:
** 评选活动的通知
:PROPERTIES:
:ID:       547829E7-9E08-4759-8C0F-7E6AD1A70BCB
:END:
区青少年活动中心，各教育指导中心，各中小学、中职校： 
    为贯彻落实《上海市科普事业“十三五”发展规划》《上海市中长期教育改革和发展规划纲要（2010—2020）》要求，全面推进学校科学素质教育，进一步提升青少年科技创新素养和实践能力，形成讲科学、爱科学、学科学、用科学的良好科技教育环境，促进品学兼优的青少年科技人才脱颖而出。同时根据市教委等部门《关于开展第十八届上海市百万青少年争创“明日科技之星”评选活动的通知》精神，经研究决定，区教育局、区科经委联合开展第十八届浦东新区青少年“明日科技之星”评选活动，现将有关事宜通知如下：

*** 一、组织机构
:PROPERTIES:
:ID:       6FD14843-654A-4897-9AAD-FBD7A2B6A91E
:END:
主办单位：浦东新区教育局   
浦东新区科技和经济委员会
承办单位：浦东新区青少年活动中心  
浦东新区青少年科普促进会
由主办单位和承办单位有关人员组成浦东新区“明日科技之星”评选活动组委会，组织活动开展，并下设活动办公室，负责活动具体实施。

*** 二、参评对象
:PROPERTIES:
:ID:       73E92263-4E8F-483E-81AD-0437DDC46099
:END:
本区中、小学和中等职业学校在读学生，分设小学组和中学组两个组别，中学组含中职校学生。
参评学生需同时符合下列条件：
（一）品学兼优，并于2020年7月前在本区中小学、中等职业技术学校就读的学生。
（二）具有科技创新成果，成果形式为科学研究论文或发明创造作品，同时其创新成果必须是在2019年2月以后完成的。曾经在历届“明日科技之星”评选活动中参评过但属二次创新的课题成果或创新作品，需由学校出具相关说明，指明新的创新点，并加盖学校公章后方可参加评选。
（三）中学组团队参评，不能超过3人，且必须为同一学校。
（四）小学组团队参评，每个团队3人，同一学校分高年级组(4-5年级)和低年级组(1-3年级)。每校各组别限报一支队伍。

*** 三、申报办法
:PROPERTIES:
:ID:       4888CB0F-8FC4-49E8-9D26-E69B4CCC540C
:END:
（一）赛前培训（2020年1月7日）
为各参评学校顺利做好申报等相关工作，现定于2020年1月7日（周二）下午2:00—4:30，在区青少年活动中心金杨点二楼多功能厅（枣庄路998弄1号）举办申报培训，请参评学校安排1名相关负责老师准时参加。 
（二）学生网上注册申报（2019年12月25日-2020年1月30日）
参评学生经学校推荐，通过“青少年明日科技之星网”（ys.shsunshine.org/kjzx），完成网上注册和申报，经学校审核通过并网上填写《学校推荐表》后，1月30日（周四）前必须完成网上提交。
（三）学校提交网上生成材料的纸质打印稿（2020年2月15日）
进入终评的学校需提交《第十八届上海市百万青少年争创“明日科技之星”评选活动申报表》一份，包括参评信息、项目简述、原创声明、个人信息、学校推荐表，申报表必须根据表内要求签字盖章。另加“摘要（项目简述）”一式八份。

*** 四、区级评选
:PROPERTIES:
:ID:       5ED987F8-2E92-433A-9318-E3823202BA06
:END:
评选活动注重对学生综合素质的测评，注重对学生研究与创作过程的评价。具体评选过程和方法如下：
（一）区级初评（2020年2月1日—2月5日）
由专家评委根据学校网上申报材料进行网上初评，确定入围区级终评名单，2月10日（周一）通过浦东新区青少年活动中心网站（www.shng.cn）公告通知栏公布。
（二）区级终评（2020年2月15日）
参评学生利用PPT对课题研究成果和探究过程进行介绍，介绍时间不超过8分钟。评委根据介绍和答辩情况，以科学性、创新性、实用性和真实性为原则进行评价。在介绍和答辩过程中，学生需出示相关原始材料，发明创造类项目必须展示作品实物。
终评过程中，还需对参评学生的科学实践能力进行测试评价。（终评地址：枣庄路998弄1号，浦东新区青少年活动中心金杨部二楼多功能厅）

*** 五、表彰奖励
:PROPERTIES:
:ID:       5D195104-6442-43E3-8178-36D0F1A3B49D
:END:
根据参评学生科技成果评审和科学实践能力测评结果，并参考学生所在学校评价，评选出第十八届浦东新区青少年“明日科技之星”246名，并择优推荐本区“明日科技之星”参加第十八上海市青少年“明日科技之星”评选活动。

*** 六、其它事项
:PROPERTIES:
:ID:       F600B756-1C50-4D31-BDCA-CF11DFE89A67
:END:
（一）信息发布
活动相关信息将在浦东新区青少年活动中心网站（www.shng.cn）相关栏目发布。
（二）活动联系
联系人：赵  骏  电话：50758778*8413  13918221452；邮箱：zhaojun98@qq.com
联系地址：浦东新区青少年活动中心金杨点301办公室（枣庄路998弄1号）
特此通知。
