#+TITLE: 八年级上数学错题
:PROPERTIES:
#+STARTUP: overview
#+STARTUP: noptag
#+STARTUP: hideblocks
#+OPTIONS: author:nil date:nil
#+TAGS: no_answer(a) \n no_pic(p)
#+LATEX_CLASS: exam
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{polynom}
#+LATEX_HEADER: \usepackage{ulem}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{tkz-euclide}
#+LATEX_HEADER: \newcommand\epart{\part}
#+LATEX_HEADER: \newcommand\degree{^\circ}
#+LATEX_HEADER: \renewcommand{\solutiontitle}{\noindent\textbf{解：}\par\noindent}
#+LATEX_HEADER: \everymath{\displaystyle}
#+LATEX_CLASS_OPTIONS: [answers]
:END:

* 重要考试
** 阶段1
*** 填空 8
当整数 $x$ = \fillin[2] 时，$\sqrt{x^{5 - x^{2}}}$ 是最简二次根式.

\begin{solution}
  \[
    \begin{cases}
      5 - x^{2} = 1 \\
      x > 0
    \end{cases}
    \begin{aligned}
      & x^2 = 4 \\
      & x = \pm 2
    \end{aligned}
    \therefore x = 2
  \]
\end{solution}

*** 填空 14
若正比例函数图像上的点到x轴的距离与到y轴距离的比为2:3,则函数的解析式为 \fillin[ $y = \frac{2}{3}x$ 或 $y=-\frac{2}{3}x$ ]

*** 填空 16
如图，点 $A_{1} (2,2)$ 在直线 $y=x$ 上，过点 $A_{1}$ 作 $A_{1}B_{1} \parallel y$ 轴交直线 $y=\frac{1}{2}x$ 于点 $B_{1}$ ，
以点 $A_{1}$ 为直角顶点， $A_{1}B_{1}$ 为直角边在 $A_{1}B_{1}$ 的右侧作等腰直角 $\triangle A_{1}B_{1}C_{1}$,
再过点 $C_{1}$ 作 $A_{2}B_{2} \parallel y$ 轴，分别交直线 $y=x$ 和 $y=\frac{1}{2}x$ 于 $A_{2}$，$B_{2}$ 两点，
以点 $A_{2}$ 为直角顶点，$A_{2}B_{2}$ 为直角边在 $A_{2}B_{2}$ 的右侧作等腰直角 $\triangle A_{2}B_{2}C_{2}$ ..,
按此规律进行下去，则等腰直角 $\triangle A_{m}B_{m}C_{m}$ 的面积为 \fillin[] . （用含正整数n的代数式表示）

*** 计算和简答 17
\[\frac{2}{b} \sqrt{ab^{5}} \times (-\frac{3}{2}\sqrt{a^{3}b} \times 3\sqrt{\frac{a}{b}} \quad (a<0,b<0)\]
\vspace*{1in}

\begin{solution}
  \[
    \begin{aligned}
    \mbox{原式} &= \frac{2 \times -3 \times 3}{b \times 2 } \sqrt{ ab^{5} \times a^{3}b \times \frac{a}{b} } \\
               &= - \frac{9}{b} \sqrt{a^{5}b^{5}} \\
               &= - \sqrt{9a^{2}b^{2}}{b} \sqrt{ab} \\
               &= - 9a^{2}b \sqrt{ab}
    \end{aligned}
  \]
\end{solution}

*** 计算和简答 21
若关于 $x$ 的一元二次方程 $(2m-1)x^{2} - 2 \sqrt{m}x + 1 = 0$ 有两个不相等的实数根。

\begin{parts}
\epart 求 $m^{2}$ 的取值范围；
\vspace*{1in}

\begin{solution}
\[
   \begin{aligned}
    & \begin{cases}
      2m - 1 \neq 0 \\
      \Delta > 0
      \end{cases} \\
    & \begin{aligned}
      \Delta &= 4m - 8m + 4 \\
             &= 4 - 4m
    \end{aligned} \\
    & \because \Delta > 0 \\
    & \begin{aligned} 
      \therefore 4 - 4m &> 0 \\
            4m &< 4 \\
             m &< 1
     \end{aligned} \\
    & \therefore 0 \leq m \le 1 \mbox{且} m \neq \frac{1}{2} \\
    & \mbox{答：} \quad 0 \leq m \le 1 \mbox{且}  m \neq \frac{1}{2} \mbox{时，原方程有两个不想等的实数根}
   \end{aligned}
\]
\end{solution}

\epart 当 $m + \frac{1}{m}=11$ 时，求 $\sqrt{m} - \frac{1}{\sqrt{m}}$ 的值。
\vspace*{1in}

\begin{solution}
\[
   \begin{aligned}
     ( \sqrt{m} - \frac{1}{ \sqrt{m} } )^{2} &= m + \frac{1}{m} - 2 \\
     \mbox{当} m + \frac{1}{m} &= 11 \mbox{时} \\
     (\sqrt{m} - \frac{1}{\sqrt{m}}) ^{2} &= 11 - 2 \\
                                          &= 9 \\
      \sqrt{m} - \frac{1}{\sqrt{m}} &= \pm 3 \\
      \therefore \sqrt{m} - \frac{1}{ \sqrt{m} } = 3 \mbox{或} -3
   \end{aligned}
\]
\end{solution}

\end{parts}

*** 计算和简答 22
已知方程 $x^{2} + 2(a+1)x + 3a^{2} + 4ab + 4b^{2} + 2 = 0$ 有2个相等的实数根，求 $a$ , $b$ 的值
\vspace*{1in}

\begin{solution}
\[
   \begin{aligned}
     & \begin{aligned}
       \Delta &= (2(a+1))^{2} - 4(3a^{2} + 4ab + 4b^{2} + 2) \\
              &= 4a^{2} + 4 + 8a - 12a^{2} - 16ab - 16b^{2} - 8 \\
              &= -8a^{2} - 4 + 8a - 16ab - 16b^{2} \\
              &= -(4a^{2} - 8a + 4) - (4a^{2} + 16ab + 16b^{2}) \\
              &= - (2a - 2)^{2} - (2a + 4b)^{2}
     \end{aligned} \\
     & \therefore \Delta = 0 \\
     & \begin{cases}
          2a - 2 = 0 \\
          2a + 4b = 0
     \end{cases} \\
     & \mbox{解得：} \quad a = 1 \quad b = - \frac{1}{2} \\
     & \mbox{答：} a \mbox{为} 1 , \quad b \mbox{为} - \frac{1}{2}
   \end{aligned}
\]
\end{solution}

*** 解答题 24
已知 $\triangle ABC$ 中，$\angle ACB = 90 \degree$ , $AC=BC$ , 点 $D$ 在线段 $BC$ 上，联结 $AD$ , 过 $A$ 作 $AE  AD$,
且 $AE=AD$ , 联结 $BE$ , 交 $AC$ 于 $F$ , 联结 $DE$ . 猜想 $BD$ 和 $CF$ 有何数量关系，并加以证明

\begin{tikzpicture}
  \tikzset{
    dot/.style={
      circle, fill=black, inner sep=1pt, outer sep=0pt
    },
    dot label/.style={
      circle, inner sep=0pt, outer sep=1pt
    },
    % style for every pics named "right angle"
    pics/right angle/.append style={
      /tikz/draw, /tikz/angle radius=5pt
    }
  }

  \coordinate (B) at (0, 0);
  \coordinate (A) at (4, 4);
  \coordinate (C) at (4, 0);

  \coordinate (D) at ($ (B)!.6!(C) $);
  \coordinate (E) at ($ (A)!1!90:(D) $);
  \coordinate (F) at (intersection of B--E and A--C);

  \draw[line width=.5pt] 
    (A) -- (B) -- (C) -- cycle
    (A) -- (E) -- (D) -- cycle
    (B) -- (E);

  \foreach \i/\angle in {A/90, B/180, C/0, D/-90, E/0, F/-30 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}

\begin{solution}
\[
   \begin{aligned}
   & \triangle ACD \cong \triangle AGE 
     \Rightarrow 
     \begin{cases}
        AC = EG = BC \\
        CD = AG
     \end{cases} \\
   & \Rightarrow \triangle FGE \cong \triangle FCB
     \Rightarrow GF = FC \\
   & BC = BD + CD \\
   & AC = GF + FC + AG \\
   & \therefore BD = GF + FC = 2CF
   \end{aligned}
\]
\end{solution}

*** 解答题 25
已知直线 $y=kx$ 过点 $(- \frac{1}{2},3)$ , $A$ 是直线 $y=kx$ 上一点，若过点 $A$ 向 $x$ 轴引垂线，垂足为 $B$ , 
且 $S_{\triangle AOB}=5$ , 求点 $B$ 的坐标。
\vspace*{1in}

\begin{solution}
\[
   \begin{aligned}
    & \because \begin{aligned}
      & y = kx \quad (k \neq 0) \mbox{过点} ( - \frac{1}{2}, 3) \\
      & \mbox{当} y = 3 , x= - \frac{1}{2} \mbox{时} \\
      & k = -6 \\
      & y = -6x \\
      \end{aligned} \\
    & \because S_{\triangle AOB} = 5 \\
    & \therefore \begin{aligned}
        6 x^{2} &= 10 \\
          x^{2} &= \frac{5}{3} \\
              x &= \pm \frac{ \sqrt{5} }{ \sqrt{3} } \\
              x &= \pm \frac{ \sqrt{15} } { 3 }
      \end{aligned} \\
    B \mbox{的坐标为} (\frac{ \sqrt{15} }{3}, 0) \mbox{或} (- \frac{ \sqrt{15} }{3}, 0) 
   \end{aligned}
\]
\end{solution}

*** 解答题 27
如图，长方形 $OABC$ 的边长，$BC=4$ ,  $AB=2$

\begin{tikzpicture}
  \tikzset{
    dot/.style={
      circle, fill=black, inner sep=1pt, outer sep=0pt
    },
    dot label/.style={
      circle, inner sep=0pt, outer sep=1pt
    },
  }

  \draw[->](-1,0)--(5,0);
  \draw[->](0,-1)--(0,3);

  \coordinate (A) at (4, 0);
  \coordinate (C) at (0, 2);
  \coordinate (B) at (4, 2);
  \coordinate (D) at (0, 0);
  \coordinate (P) at ($ (A)!.6!(B) $);

  % \draw[->](0,-1)--(0,3);

  \draw[line width=.5pt] 
    (C) -- (B)
    (A) -- (B)
    ($ (D)!-.2!(P) $) -- ($ (D)!1.2!(P) $)
    ;

  \foreach \i/\angle in {A/-90, B/90, C/60, D/120, P/0 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}

\begin{parts}
\epart 直线 $y=kx \quad (k \neq 0)$ 交边 $AB$ 于点 $P$ , 求 $k$ 的取值范围；
\vspace*{1in}


\begin{solution}
\[
   \begin{aligned}
   & \mbox{当} x = 4 \mbox{时} \\
   & y = 4k \\
   & \because P \mbox{在} BA \mbox{之间} \\
   & \therefore 0 \leq 4k \leq 2 \\
   & \because k \neq 0 \\
   & \therefore 0 < k < \frac{1}{2}
   \end{aligned}
\]
\end{solution}

\epart 直线 $y=kx \quad (k \neq 0)$ 是否可能将长方形 $OABC$ 的面积分成 2:3 两部分？若能，求出 $k$ 的值，若不能，说明理由。
\vspace*{1in}

\begin{solution}
\[
   \begin{aligned}
     & \begin{aligned}
          S_{\Box}DABC &= ab \\
                       &= 8
       \end{aligned} \\
     & \begin{aligned}
       1. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDA = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & x = 4 \\
          & \therefore y1 = \frac{8}{5} \quad y2 = \frac{12}{5} \\
          & k1 = \frac{2}{5} \quad k2=\frac{3}{5} \\
       2. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDC = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & y = 0 \\
          & \therefore X_{1} = \frac{15}{5} \quad x_{2} = frac{24}{5} \\
          & k4 = \frac{5}{8}
       \end{aligned} \\
     & \mbox{综上所述} \mbox{当} k = \frac{5}{8} \mbox{或} \frac{2}{5} \mbox{或} \frac{3}{5} \mbox{时，可以}
   \end{aligned}
\]
\end{solution}

\end{parts}

* 周测
* 欣竹
** 待补充
*** 熟练 1.2 
方程 $5x^{2}-4\sqrt{5}x+4=0$ 的根号判别式的值为 \fillin[0] ，该方程 \fillin[有] 实数跟。
*** 熟练 1.3
关于x的一元二次方程 $(m-1)x^{2}+2mx+m+3=2$ 有两个不相等的实数根，那么m的范围 \fillin[ $m < 3/2 \mbox{且} m \ne 1$ ]

*** 熟练  2.1 计算各题
当 $m$ 取何值时，关于 $x$ 的方程 $mx^{2} + 2x -1 = 0$ 有两个实数根:

\begin{solution}
  \[
    \begin{aligned}
    & \begin{cases}
      m \neq 0 \\qrt

      \Delta > 0 \\
    \end{cases} \\
    & \begin{aligned}
      & \begin{aligned}
        \Delta &= 6^{2} - 4ac \\
               &= 4 + 4m \\
        \end{aligned} \\
        & 4+4m \geq 0 \\
        & m \geq -1 \\
      \end{aligned} \\
    \end{aligned}
  \]
\end{solution}

*** 拓展 1
求证：不论实数 $m$ 取何值，关于 $x$ 的方程 $(m^{2} + 1)x^{2}+2mx+m^{2}+4=0$ 没有实数根。

\begin{solution}
  \[
    \begin{aligned}
      & \Delta = -4m^{4} -16m^{2} - 16 \\
      & \because m^{4} \geq 0 \qquad m^{2} \geq 0 \\
      & \therefore \Delta \le 0 \\
      & \therefore \mbox{无实根} \\
    \end{aligned}
  \]
\end{solution}

*** 探究 1
$k$ 为何值时，方程 $(k-1)x^{2}-(2k+3)x+(k+3)=0$ 有实数根？

\begin{solution}

\end{solution}

*** 探究 2
若 $m$ 为非负整数，且一元二次方程 $(1-m^{2})x^{2}+2(1-m)x-1=0$

\begin{solution}

\end{solution}
