#+TITLE: 八年级上数学错题
:PROPERTIES:
#+STARTUP: content
#+STARTUP: noptag
#+STARTUP: hideblocks
#+OPTIONS: author:nil date:nil
#+TAGS: no_answer(a) \e error(p)
#+LATEX_CLASS: exam
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{polynom}
#+LATEX_HEADER: \usepackage{ulem}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{tkz-euclide}
#+LATEX_HEADER: \newcommand\epart{\part}
#+LATEX_HEADER: \newcommand\degree{^\circ}
#+LATEX_HEADER: \renewcommand{\solutiontitle}{\noindent\textbf{解：}\par\noindent}
#+LATEX_HEADER: \everymath{\displaystyle}
#+LATEX_CLASS_OPTIONS: [answers]

#+begin_src latex
\tikzset{
  dot/.style={
    circle, fill=black, inner sep=1pt, outer sep=0pt
  },
  dot label/.style={
    circle, inner sep=0pt, outer sep=1pt
  },
  % style for every pics named "right angle"
  pics/right angle/.append style={
    /tikz/draw, /tikz/angle radius=5pt
  }
}
#+end_src
:END:

* 重要考试
** 小达人
*** 填空 12                                                       :no_answer:
在实数范围内分解因式: $(x^{2} + x)^{2} - 2x(x^{2} + x) - 2 =$ \fillin[]
*** 填空 15                                                       :no_answer:
对于方程 $x^{2} - 2 |x| + 2 = m$ , 如果方程实根的个数恰为 $3$ 个，则 $m$ 值等于 \fillin[]

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
     & |x|^{2} - |x| = m - 2 \\
     & (|x| -1)^{2} = m - 1 \\
     & m - 1 > 0 \\
     & \begin{cases}
         x^{2} = |x|^{2} \\
         |x| - 1 = \sqrt{m - 1}
       \end{cases} \\
     & \rightarrow |x| = 1 + \sqrt{m - 1} \\
     & 
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 21                                                     :no_answer:
如果 $2x^{2} + xy - y^{2} + my - 2$ 在实数范围内能分解成两个一次因式之积，求实数 $m$ 的值，并将它分解。

*** 解答题 23                                                     :no_answer:
某批发商以每件 $50$ 元的价格购进 $800$ 件T恤，第一个月以单价 $80$ 元销售，售出了 $200$ 件；
第二个月如果单价不变，预计仍可售出 $200$ 件，批发商为增加销售量，决定降价销售，根据市场调查，单价每降低 $1$ 元，可多售出 $10$ 件，
但最低单价应高于购进的价格，第二个月结束后，批发商将对剩余的T恤一次性清仓销售，清仓时单价为 $40$ 元。设第二个月单价降低 $x$ 元。

#+LATEX: \begin{parts}

\epart 填空（不需化简）：

| 时间         | 第一个月 | 第二个月 | 清仓时 |
|--------------+----------+----------+--------|
| 单价（元）   |       80 |          |  40    |
| 销售量（件） |      200 |          |        |

#+LATEX: \begin{solution}
| 时间         | 第一个月 | 第二个月    | 清仓时                |
|--------------+----------+-------------+-----------------------|
| 单价（元）   |       80 | $80-x$      | 40                    |
| 销售量（件） |      200 | $200 + 10x$ | $800 - 200 - 200-10x$ |
#+LATEX: \end{solution}

\epart 如果批发商希望通过销售这批T恤获利9000元，那么第二个月的单价应是多少元？
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    (30 - x)(200 + 10x) + 10(400 - 10x) &= 3000 \\
    600 + 10x - x^{2} &= 200
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 计算 25                                                       :no_answer:
已知：如图点 $A(6,8)$ 在正比例函数图像上，点 $B$ 坐标 $(12,0)$ ,联结 $AB$ , $A0=AB=10$ ,
点 $C$ 是线段 $AB$ 的中点，点 $P$ 在线段 $B0$ 上以每秒2个单位的速度由点 $B$ 向点 $O$ 运动，
点 $Q$ 在线段 $AO$ 上由点 $A$ 向点 $O$ 运动，$P$ 、$Q$ 两点同时运动，同时停止，运动时间为 $t$ 秒。

#+begin_src latex :noweb yes
\begin{tikzpicture}[scale=0.4]
\draw[->](-2.5,0)--(14.5,0) node at (15,0){$x$};
\draw[->](0,-2.5)--(0,9.5) node at (0,10){$y$};

\foreach \i in {-2,-1,1,2,3,4,5,6,7,8,9,10,11,12,13,14} {
    \draw (\i,0) --+ (0,-0.2);
}

\foreach \i in {-2,-1,1,2,3,4,5,6,7,8,9} {
    \draw (0,\i) --+ (-0.2,0);
}

\coordinate (O) at (0,0);
\coordinate (A) at (6,8);
\coordinate (B) at (12,0);
\coordinate (C) at ($ (B)!.5!(A) $);


\coordinate (P) at ($ (O)!.6!(B) $);
\coordinate (Q) at ($ (O)!.7!(A) $);

\foreach \i/\angle in {O/-45,A/120,B/-90,C/45,P/-90,Q/135} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\draw[line width=.5pt]
  (O) -- (A) -- (B)
  (Q) -- (P) -- (C);

\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\epart 求该正比例函数的解析式；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
    \begin{aligned}
      & y = kx (k \neq 0) \\
      & \mbox{当} y = 8, x = 6 \mbox{时} \\
      & 8 = k6 \\
      & k = \frac{4}{3} \\
      & \mbox{答：该正比例函数的解析式为} y = \frac{4}{3}k
    \end{aligned}
\]
\end{solution}
#+end_src

\epart 联结 $CP$ ,在点 $P$ 、$Q$ 运动过程中，$\triangle OPQ$ 与 $\triangle BPC$ 是否全等？ 如果全等，请求出点 $Q$ 的运动速度；如果不全等，请说明理由。
\vspace*{1in}

#+begin_src latex
\begin{solution}
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 阶段1
*** 填空 8
当整数 $x$ = \fillin[2] 时，$\sqrt{x^{5 - x^{2}}}$ 是最简二次根式.

\begin{solution}
  \[
    \begin{cases}
      5 - x^{2} = 1 \\
      x > 0
    \end{cases}
    \begin{aligned}
      & x^2 = 4 \\
      & x = \pm 2
    \end{aligned}
    \therefore x = 2
  \]
\end{solution}

*** 填空 14
若正比例函数图像上的点到x轴的距离与到y轴距离的比为2:3,则函数的解析式为 \fillin[ $y = \frac{2}{3}x$ 或 $y=-\frac{2}{3}x$ ]

*** 填空 16                                                       :no_answer:
如图，点 $A_{1} (2,2)$ 在直线 $y=x$ 上，过点 $A_{1}$ 作 $A_{1}B_{1} \parallel y$ 轴交直线 $y=\frac{1}{2}x$ 于点 $B_{1}$ ，
以点 $A_{1}$ 为直角顶点， $A_{1}B_{1}$ 为直角边在 $A_{1}B_{1}$ 的右侧作等腰直角 $\triangle A_{1}B_{1}C_{1}$,
再过点 $C_{1}$ 作 $A_{2}B_{2} \parallel y$ 轴，分别交直线 $y=x$ 和 $y=\frac{1}{2}x$ 于 $A_{2}$，$B_{2}$ 两点，
以点 $A_{2}$ 为直角顶点，$A_{2}B_{2}$ 为直角边在 $A_{2}B_{2}$ 的右侧作等腰直角 $\triangle A_{2}B_{2}C_{2}$ ..,
按此规律进行下去，则等腰直角 $\triangle A_{m}B_{m}C_{m}$ 的面积为 \fillin[] . （用含正整数n的代数式表示）

#+begin_src latex
\begin{tikzpicture}
  \draw[->](-1,0)--(4.7,0) node at (5,0){$x$};
  \draw[->](0,-1)--(0,2.7) node at (0,3){$y$};

  \draw[domain=-0.5:2.5,name path = Fn1] plot(\x,\x) node at (2.7,2.7){$y=x$};
  \draw[domain=-0.5:3.7,name path = Fn2] plot(\x,0.5*\x) node at (4,2){$y=\frac{1}{2}x$};

  %三角形1
  \path[name path=l1] (0.8,0) --+ (0, 2.7);
  \fill[name intersections={of=l1 and Fn1,by=A1},
        name intersections={of=l1 and Fn2,by=B1}];
  \coordinate (C1) at ($ (A1)!1!90:(B1) $);
  \draw[line width=.5pt]  (A1) -- (B1) -- (C1) -- cycle;

  \foreach \i/\angle in {A1/90,B1/-90,C1/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  %三角形2
  \path[name path=l2] ($(C1) - (0, 3)$) -- ($(C1) + (0, 3)$);
  \fill[name intersections={of=l2 and Fn1,by=A2},
        name intersections={of=l2 and Fn2,by=B2}];
  \coordinate (C2) at ($ (A2)!1!90:(B2) $);
  \draw[line width=.5pt]  (A2) -- (B2) -- (C2) -- cycle;

  \foreach \i/\angle in {A2/90,B2/-90,C2/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  %三角形3
  \path[name path=l3] ($(C2) - (0, 3)$) -- ($(C2) + (0, 3)$);
  \fill[name intersections={of=l3 and Fn1,by=A3},
        name intersections={of=l3 and Fn2,by=B3}];
  \coordinate (C3) at ($ (A3)!1!90:(B3) $);
  \draw[line width=.5pt]  (A3) -- (B3) -- (C3) -- cycle;

  \foreach \i/\angle in {A3/90,B3/-90,C3/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  \node[draw] at ($(C3) + (0.8,0.8)$) {....};
\end{tikzpicture}
#+end_src

*** 计算和简答 17
\[\frac{2}{b} \sqrt{ab^{5}} \times (-\frac{3}{2}\sqrt{a^{3}b} \times 3\sqrt{\frac{a}{b}} \quad (a<0,b<0)\]
\vspace*{1in}

#+begin_src latex
\begin{solution}
  \[
    \begin{aligned}
    \mbox{原式} &= \frac{2 \times -3 \times 3}{b \times 2 } \sqrt{ ab^{5} \times a^{3}b \times \frac{a}{b} } \\
               &= - \frac{9}{b} \sqrt{a^{5}b^{5}} \\
               &= - \sqrt{9a^{2}b^{2}}{b} \sqrt{ab} \\
               &= - 9a^{2}b \sqrt{ab}
    \end{aligned}
  \]
\end{solution}
#+end_src

*** 计算和简答 21
若关于 $x$ 的一元二次方程 $(2m-1)x^{2} - 2 \sqrt{m}x + 1 = 0$ 有两个不相等的实数根。

#+LATEX: \begin{parts}
\epart 求 $m^{2}$ 的取值范围；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
    & \begin{cases}
      2m - 1 \neq 0 \\
      \Delta > 0
      \end{cases} \\
    & \begin{aligned}
      \Delta &= 4m - 8m + 4 \\
             &= 4 - 4m
    \end{aligned} \\
    & \because \Delta > 0 \\
    & \begin{aligned} 
      \therefore 4 - 4m &> 0 \\
            4m &< 4 \\
             m &< 1
     \end{aligned} \\
    & \therefore 0 \leq m \le 1 \mbox{且} m \neq \frac{1}{2} \\
    & \mbox{答：} \quad 0 \leq m \le 1 \mbox{且}  m \neq \frac{1}{2} \mbox{时，原方程有两个不想等的实数根}
   \end{aligned}
\]
\end{solution}
#+end_src

\epart 当 $m + \frac{1}{m}=11$ 时，求 $\sqrt{m} - \frac{1}{\sqrt{m}}$ 的值。
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
     ( \sqrt{m} - \frac{1}{ \sqrt{m} } )^{2} &= m + \frac{1}{m} - 2 \\
     \mbox{当} m + \frac{1}{m} &= 11 \mbox{时} \\
     (\sqrt{m} - \frac{1}{\sqrt{m}}) ^{2} &= 11 - 2 \\
                                          &= 9 \\
      \sqrt{m} - \frac{1}{\sqrt{m}} &= \pm 3 \\
      \therefore \sqrt{m} - \frac{1}{ \sqrt{m} } = 3 \mbox{或} -3
   \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 计算和简答 22
已知方程 $x^{2} + 2(a+1)x + 3a^{2} + 4ab + 4b^{2} + 2 = 0$ 有2个相等的实数根，求 $a$ , $b$ 的值
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
     & \begin{aligned}
       \Delta &= (2(a+1))^{2} - 4(3a^{2} + 4ab + 4b^{2} + 2) \\
              &= 4a^{2} + 4 + 8a - 12a^{2} - 16ab - 16b^{2} - 8 \\
              &= -8a^{2} - 4 + 8a - 16ab - 16b^{2} \\
              &= -(4a^{2} - 8a + 4) - (4a^{2} + 16ab + 16b^{2}) \\
              &= - (2a - 2)^{2} - (2a + 4b)^{2}
     \end{aligned} \\
     & \therefore \Delta = 0 \\
     & \begin{cases}
          2a - 2 = 0 \\
          2a + 4b = 0
     \end{cases} \\
     & \mbox{解得：} \quad a = 1 \quad b = - \frac{1}{2} \\
     & \mbox{答：} a \mbox{为} 1 , \quad b \mbox{为} - \frac{1}{2}
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 24
已知 $\triangle ABC$ 中，$\angle ACB = 90 \degree$ , $AC=BC$ , 点 $D$ 在线段 $BC$ 上，联结 $AD$ , 过 $A$ 作 $AE  AD$,
且 $AE=AD$ , 联结 $BE$ , 交 $AC$ 于 $F$ , 联结 $DE$ . 猜想 $BD$ 和 $CF$ 有何数量关系，并加以证明

#+name: picture
#+begin_src latex
\begin{tikzpicture}
  \coordinate (B) at (0, 0);
  \coordinate (A) at (4, 4);
  \coordinate (C) at (4, 0);

  \coordinate (D) at ($ (B)!.6!(C) $);
  \coordinate (E) at ($ (A)!1!90:(D) $);
  \coordinate (F) at (intersection of B--E and A--C);

  \draw[line width=.5pt] 
    (A) -- (B) -- (C) -- cycle
    (A) -- (E) -- (D) -- cycle
    (B) -- (E);

  \foreach \i/\angle in {A/90, B/180, C/0, D/-90, E/0, F/-30 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}
#+end_src

#+name: solution
#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
   & \triangle ACD \cong \triangle AGE 
     \Rightarrow 
     \begin{cases}
        AC = EG = BC \\
        CD = AG
     \end{cases} \\
   & \Rightarrow \triangle FGE \cong \triangle FCB
     \Rightarrow GF = FC \\
   & BC = BD + CD \\
   & AC = GF + FC + AG \\
   & \therefore BD = GF + FC = 2CF
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 25
已知直线 $y=kx$ 过点 $(- \frac{1}{2},3)$ , $A$ 是直线 $y=kx$ 上一点，若过点 $A$ 向 $x$ 轴引垂线，垂足为 $B$ , 
且 $S_{\triangle AOB}=5$ , 求点 $B$ 的坐标。
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
    & \because \begin{aligned}
      & y = kx \quad (k \neq 0) \mbox{过点} ( - \frac{1}{2}, 3) \\
      & \mbox{当} y = 3 , x= - \frac{1}{2} \mbox{时} \\
      & k = -6 \\
      & y = -6x \\
      \end{aligned} \\
    & \because S_{\triangle AOB} = 5 \\
    & \therefore \begin{aligned}
        6 x^{2} &= 10 \\
          x^{2} &= \frac{5}{3} \\
              x &= \pm \frac{ \sqrt{5} }{ \sqrt{3} } \\
              x &= \pm \frac{ \sqrt{15} } { 3 }
      \end{aligned} \\
    B \mbox{的坐标为} (\frac{ \sqrt{15} }{3}, 0) \mbox{或} (- \frac{ \sqrt{15} }{3}, 0) 
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 27
如图，长方形 $OABC$ 的边长，$BC=4$ ,  $AB=2$

#+begin_src latex
\begin{tikzpicture}
  \tikzset{
    dot/.style={
      circle, fill=black, inner sep=1pt, outer sep=0pt
    },
    dot label/.style={
      circle, inner sep=0pt, outer sep=1pt
    },
  }

  \draw[->](-1,0)--(5,0);
  \draw[->](0,-1)--(0,3);

  \coordinate (A) at (4, 0);
  \coordinate (C) at (0, 2);
  \coordinate (B) at (4, 2);
  \coordinate (D) at (0, 0);
  \coordinate (P) at ($ (A)!.6!(B) $);

  % \draw[->](0,-1)--(0,3);

  \draw[line width=.5pt] 
    (C) -- (B)
    (A) -- (B)
    ($ (D)!-.2!(P) $) -- ($ (D)!1.2!(P) $)
    ;

  \foreach \i/\angle in {A/-90, B/90, C/60, D/120, P/0 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\epart 直线 $y=kx \quad (k \neq 0)$ 交边 $AB$ 于点 $P$ , 求 $k$ 的取值范围；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
   & \mbox{当} x = 4 \mbox{时} \\
   & y = 4k \\
   & \because P \mbox{在} BA \mbox{之间} \\
   & \therefore 0 \leq 4k \leq 2 \\
   & \because k \neq 0 \\
   & \therefore 0 < k < \frac{1}{2}
   \end{aligned}
\]
\end{solution}
#+end_src

\epart 直线 $y=kx \quad (k \neq 0)$ 是否可能将长方形 $OABC$ 的面积分成 2:3 两部分？若能，求出 $k$ 的值，若不能，说明理由。
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
     & \begin{aligned}
          S_{\Box}DABC &= ab \\
                       &= 8
       \end{aligned} \\
     & \begin{aligned}
       1. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDA = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & x = 4 \\
          & \therefore y1 = \frac{8}{5} \quad y2 = \frac{12}{5} \\
          & k1 = \frac{2}{5} \quad k2=\frac{3}{5} \\
       2. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDC = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & y = 0 \\
          & \therefore X_{1} = \frac{15}{5} \quad x_{2} = frac{24}{5} \\
          & k4 = \frac{5}{8}
       \end{aligned} \\
     & \mbox{综上所述} \mbox{当} k = \frac{5}{8} \mbox{或} \frac{2}{5} \mbox{或} \frac{3}{5} \mbox{时，可以}
   \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

* 专项练习
** 正比例函数和反比例函数
*** 填空1
在问题研究过程中，可以取不同数值的量叫 \fillin[自变量]。
保持数值不变的量叫做 \fillin[常量]。
表达两个变量之间依赖关系的数学式子称为 \fillin[函数解析式]。

*** 填空9
函数有三种表示法，分别为 \fillin[图像法] ， \fillin[列表发] ， \fillin[解析法] 。

*** 填空21
$y$ 与 $3x$ 成正比例，当 $x=8$ 时，$y=-12$ ,则 $y$ 与 $x$ 的函数解析式为 \fillin[ $y=-\frac{3}{2}x$ ]。

*** 填空25
下列函数中，$y$ 随 $x$ 的增大而减少的函数是 \fillin[]

#+begin_src latex
\begin{oneparchoices}
  \choice $y=2x$
  \choice $y=\frac{1}{x}$
  \choice $y=- \frac{1}{x}$
  \correctchoice $y=\frac{2}{x} (x > 0)$
\end{oneparchoices}
#+end_src

*** 填空题26
甲、乙两地相距 $100$ 千米，某人开车从甲地到乙地，那么它的速度 $v$ (千米／小时）与时间 $t$ (时）之间的函数关系用图象表示大致为 \fillin[D]

#+name: pic.正比例函数和反比例函数.25.base
#+begin_src latex :noweb yes :exports none
\draw[->](-1,0)--(1,0) node at (1,-0.2){$t$};
\draw[->](0,-1)--(0,1) node at (-0.2,1){$v$};
\draw node at (0.2, -0.2){$O$};
#+end_src

#+begin_src latex :noweb yes
\begin{oneparchoices}
\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-0.8:0.8] plot(\x,\x);
\end{tikzpicture}

\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=0:0.8] plot(\x,\x);
\end{tikzpicture}

\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-1/0.8:-0.8] plot(\x,{1/\x});
\end{tikzpicture}

\correctchoice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-1/0.8:-0.8] plot(\x,{1/\x});
\draw[domain=1/0.8:0.8] plot(\x,{1/\x});
\end{tikzpicture}

\end{oneparchoices}
#+end_src

*** 填空题27
如果点 $A(x1,y1)$ 、$B(x2,y2)$ 在反比例函数 $y=\frac{k}{x} (k<0)$ 的图象上，
如果 $x_1 > x_2 > 0$ 则 $y_{1}$ 与 $y_{2}$ ,的大小关系是 \fillin[A]

#+begin_src latex
\begin{oneparchoices}
\correctchoice $y_{1} > y_{2}$
\choice $y_{1} < y_{2}$
\choice $y_{1} = y_{2}$
\choice 不能确定
\end{oneparchoices}
#+end_src

*** 问答题29                                                          :error:
已知 $y = y_1 + y_2$ , $y_1$ 与 $x^2$ 成正比例， $y_2$ 与 $x-1$ 成反比例，当 $x=-1$ 时，$y=3$ ； 当 $x=2$ 时，$y=-3$ ，

#+LATEX: \begin{parts}
\part 求 $y$ 与 $x$ 之间的函数关系式；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \mbox{设正比例函数解析式为} y_{1}=k_{1}x^{2} \quad (k_{1} \neq 0) \\
    & \mbox{反比例函数解析式为} y_{2}=\frac{k_{2}}{x - 1} \quad (k_{2} \neq 0) \\
    & \mbox{当} x = -1 \mbox{时} , y = 3 \\
    & \Rightarrow 3 = k_{1} - \frac{k_{2}}{2} \\
    & \mbox{当} x = 2 \mbox{时} , y = -3 \\
    & \Rightarrow -3 = 4k_{1} + k_{2} \\
    & \mbox{解得} k_{1} = \frac{1}{2} \quad k_{2} = -5 \\
    & \therefore y = \frac{x^{2}}{2} - \frac{5}{x - 1}
  \end{aligned}
\]
\end{solution}
#+end_src

\part 当 $x = \sqrt{2}$ 时，求 $y$ 的值。
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \mbox{当} x = \sqrt{2} \mbox{时} \\
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 问答题31                                                      :no_answer:
如图，直线 $l$ 交 $x$ 轴、$y$ 轴与点 $A$ 、$B$ ，与反比例函数额图像交于 $C$ 、 $D$ 两点，如果 $A(2,0)$ ，
点 $C$ 、$D$ 分别在一、三象限，且 $OA = OB = AC = BD$ ， 求反比例函数的解析式。

#+begin_src latex
\begin{tikzpicture}[scale=0.6]
\draw[->](-5,0)--(5,0) node at (5,-0.5){$x$};
\draw[->](0,-5)--(0,5) node at (-0.5,5){$y$};

\draw[domain=1/0.25:0.25, name path=F1] plot(\x,{1/\x});
\draw[domain=-1/0.25:-0.25, name path=F2] plot(\x,{1/\x});

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 0);
\coordinate (B) at (0, -2);

\draw[-,name path=line]($(A)!2!(B)$)--($(B)!2!(A)$) ;

\fill[name intersections={of=F1 and line,by=C},
      name intersections={of=F2 and line,by=D}];

\foreach \i/\angle in {O/-145,A/-90,B/0,C/90,D/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题33
如图，在 $\triangle AOB$ 中， $AB=OB$ ,点 $B$ 在双曲线上，点 $A$ 的坐标为 $(2,0)$ , $S_{\triangle ABO}=4$ ,
求点 $B$ 所在双曲线的函数解析式。

#+begin_src latex
\begin{tikzpicture}
\draw[->](-1,0)--(2.5,0) node at (2.5,-0.5){$x$};
\draw[->](0,-2.5)--(0,0.5) node at (-0.5,0.5){$y$};

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 0);

\draw[domain=1/0.5:0.5, name path=F1] plot(\x,{-1/\x});

\path[name path=line] ($(O)!.5!(A)$) --+ (0,-2.5);
\fill[name intersections={of=F1 and line,by=B}];

\draw[-] (O) -- (B) -- (A);

\foreach \i/\angle in {O/-145,A/-90,B/-45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \because AB = OB \\
    & \therefore OE = OA = 1 \\
    & S_{\triangle AOB} = \frac{1}{2} \times OA \times BC = 4 \\
    & \therefore BC = 4 \\
    & \therefore y = \frac{4}{x}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题36                                                      :no_answer:
已知双曲线上两点 $A(2,4)$ , $C(4,2)$ , 且 $AB \perp OB$ , $CD \ perp OD$ ,

#+begin_src latex
\begin{tikzpicture}[scale=0.5]
\draw[->](-1,0)--(9,0) node at (9,-0.25){$x$};
\draw[->](0,-1)--(0,9) node at (-0.25,9){$y$};

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 4);
\coordinate (C) at (4, 2);
\coordinate (B) at ($(O)!(A)!($(O) + (10,0)$)$);
\coordinate (D) at ($(O)!(C)!($(O) + (10,0)$)$);
\coordinate (E) at (intersection of A--B and O--C);

\draw[domain=1:8, name path=F1] plot(\x,{8/\x});
\draw[-]
  (O) -- (A) -- (B)
  (O) -- (C) -- (D);

\foreach \i/\angle in {O/-145,A/-90,B/-90,C/-45,D/-90,E/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\part
双曲线的函数解析式；
\vspace*{1in}

#+begin_src latex
\begin{solution}
$$y=\frac{8}{x}$$
\end{solution}
#+end_src

\part
$\triangle OAB$ 的面积；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[ \S_{\triangle OAB} = \frac{|k|}{2} = \frac{8}{2} = 4 \]
\end{solution}
#+end_src

\part
$\triangle OAC$ 的面积；
\vspace*{1in}

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \because S_{\triangle AOB} = S_{\triangle OCD} \\
    & \therefore S_{\triangle AOE} = S_{ECDB} \\
    & \therefore S_{\triangle AOC} = S_{ABDC} \\
    & S_{ABDC} = S_{\triangle AOB} \frac{(2 + 4)2}{2} = 6
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

* 周测
* 欣竹
** 待补充
*** 熟练 1.2 
方程 $5x^{2}-4\sqrt{5}x+4=0$ 的根号判别式的值为 \fillin[0] ，该方程 \fillin[有] 实数跟。
*** 熟练 1.3
关于x的一元二次方程 $(m-1)x^{2}+2mx+m+3=2$ 有两个不相等的实数根，那么m的范围 \fillin[ $m < 3/2 \mbox{且} m \ne 1$ ]

*** 熟练  2.1
计算各题
当 $m$ 取何值时，关于 $x$ 的方程 $mx^{2} + 2x -1 = 0$ 有两个实数根:

\begin{solution}
  \[
    \begin{aligned}
    & \begin{cases}
      m \neq 0 \\qrt

      \Delta > 0 \\
    \end{cases} \\
    & \begin{aligned}
      & \begin{aligned}
        \Delta &= 6^{2} - 4ac \\
               &= 4 + 4m \\
        \end{aligned} \\
        & 4+4m \geq 0 \\
        & m \geq -1 \\
      \end{aligned} \\
    \end{aligned}
  \]
\end{solution}

*** 拓展 1
求证：不论实数 $m$ 取何值，关于 $x$ 的方程 $(m^{2} + 1)x^{2}+2mx+m^{2}+4=0$ 没有实数根。

\begin{solution}
  \[
    \begin{aligned}
      & \Delta = -4m^{4} -16m^{2} - 16 \\
      & \because m^{4} \geq 0 \qquad m^{2} \geq 0 \\
      & \therefore \Delta \le 0 \\
      & \therefore \mbox{无实根} \\
    \end{aligned}
  \]
\end{solution}

*** 探究 1
$k$ 为何值时，方程 $(k-1)x^{2}-(2k+3)x+(k+3)=0$ 有实数根？

\begin{solution}

\end{solution}

*** 探究 2
若 $m$ 为非负整数，且一元二次方程 $(1-m^{2})x^{2}+2(1-m)x-1=0$

\begin{solution}

\end{solution}
