#+TITLE: 八年级上数学错题
:PROPERTIES:
#+STARTUP: overview
#+STARTUP: noptag
#+STARTUP: hideblocks
#+OPTIONS: author:nil date:nil
#+TAGS: no_answer(a) \e error(p)
#+LATEX_CLASS: exam
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{polynom}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \usepackage{ulem}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{tkz-euclide}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \newcommand\epart{\part}
#+LATEX_HEADER: \newcommand\degree{^\circ}
#+LATEX_HEADER: \renewcommand{\solutiontitle}{\noindent\textbf{解：}\par\noindent}
#+LATEX_HEADER: \everymath{\displaystyle}
#+LATEX_CLASS_OPTIONS: [answers]

#+begin_src latex
\tikzset{
  dot/.style={
    circle, fill=black, inner sep=1pt, outer sep=0pt
  },
  dot label/.style={
    circle, inner sep=0pt, outer sep=1pt
  },
  % style for every pics named "right angle"
  pics/right angle/.append style={
    /tikz/draw, /tikz/angle radius=5pt
  }
}

%平行
\newcommand\pxx{%
\mathrel{\text{\tikz[baseline] \draw (0em,-0.3ex) -- (.4em,1.7ex) (.2em,-0.3ex) -- (.6em,1.7ex);}%
}}
#+end_src
:END:

* 重要考试
** 小达人
*** 填空 12                                                       :no_answer:
在实数范围内分解因式: $(x^{2} + x)^{2} - 2x(x^{2} + x) - 2 =$ \fillin[]
*** 填空 15                                                       :no_answer:
对于方程 $x^{2} - 2 |x| + 2 = m$ , 如果方程实根的个数恰为 $3$ 个，则 $m$ 值等于 \fillin[]

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
     & |x|^{2} - |x| = m - 2 \\
     & (|x| -1)^{2} = m - 1 \\
     & m - 1 > 0 \\
     & \begin{cases}
         x^{2} = |x|^{2} \\
         |x| - 1 = \sqrt{m - 1}
       \end{cases} \\
     & \rightarrow |x| = 1 + \sqrt{m - 1} \\
     & 
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 21                                                     :no_answer:
如果 $2x^{2} + xy - y^{2} + my - 2$ 在实数范围内能分解成两个一次因式之积，求实数 $m$ 的值，并将它分解。

*** 解答题 23                                                     :no_answer:
某批发商以每件 $50$ 元的价格购进 $800$ 件T恤，第一个月以单价 $80$ 元销售，售出了 $200$ 件；
第二个月如果单价不变，预计仍可售出 $200$ 件，批发商为增加销售量，决定降价销售，根据市场调查，单价每降低 $1$ 元，可多售出 $10$ 件，
但最低单价应高于购进的价格，第二个月结束后，批发商将对剩余的T恤一次性清仓销售，清仓时单价为 $40$ 元。设第二个月单价降低 $x$ 元。

#+LATEX: \begin{parts}

\epart 填空（不需化简）：

| 时间         | 第一个月 | 第二个月 | 清仓时 |
|--------------+----------+----------+--------|
| 单价（元）   |       80 |          |  40    |
| 销售量（件） |      200 |          |        |

#+LATEX: \begin{solution}
| 时间         | 第一个月 | 第二个月    | 清仓时                |
|--------------+----------+-------------+-----------------------|
| 单价（元）   |       80 | $80-x$      | 40                    |
| 销售量（件） |      200 | $200 + 10x$ | $800 - 200 - 200-10x$ |
#+LATEX: \end{solution}

\epart 如果批发商希望通过销售这批T恤获利9000元，那么第二个月的单价应是多少元？

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    (30 - x)(200 + 10x) + 10(400 - 10x) &= 3000 \\
    600 + 10x - x^{2} &= 200
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 计算 25                                                       :no_answer:
已知：如图点 $A(6,8)$ 在正比例函数图像上，点 $B$ 坐标 $(12,0)$ ,联结 $AB$ , $A0=AB=10$ ,
点 $C$ 是线段 $AB$ 的中点，点 $P$ 在线段 $B0$ 上以每秒2个单位的速度由点 $B$ 向点 $O$ 运动，
点 $Q$ 在线段 $AO$ 上由点 $A$ 向点 $O$ 运动，$P$ 、$Q$ 两点同时运动，同时停止，运动时间为 $t$ 秒。

#+begin_src latex :noweb yes
\begin{tikzpicture}[scale=0.4]
\draw[->](-2.5,0)--(14.5,0) node at (15,0){$x$};
\draw[->](0,-2.5)--(0,9.5) node at (0,10){$y$};

\foreach \i in {-2,-1,1,2,3,4,5,6,7,8,9,10,11,12,13,14} {
    \draw (\i,0) --+ (0,-0.2);
}

\foreach \i in {-2,-1,1,2,3,4,5,6,7,8,9} {
    \draw (0,\i) --+ (-0.2,0);
}

\coordinate (O) at (0,0);
\coordinate (A) at (6,8);
\coordinate (B) at (12,0);
\coordinate (C) at ($ (B)!.5!(A) $);


\coordinate (P) at ($ (O)!.6!(B) $);
\coordinate (Q) at ($ (O)!.7!(A) $);

\foreach \i/\angle in {O/-45,A/120,B/-90,C/45,P/-90,Q/135} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\draw[line width=.5pt]
  (O) -- (A) -- (B)
  (Q) -- (P) -- (C);

\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\epart 求该正比例函数的解析式；

#+begin_src latex
\begin{solution}[1in]
\[
    \begin{aligned}
      & y = kx (k \neq 0) \\
      & \mbox{当} y = 8, x = 6 \mbox{时} \\
      & 8 = k6 \\
      & k = \frac{4}{3} \\
      & \mbox{答：该正比例函数的解析式为} y = \frac{4}{3}k
    \end{aligned}
\]
\end{solution}
#+end_src

\epart 联结 $CP$ ,在点 $P$ 、$Q$ 运动过程中，$\triangle OPQ$ 与 $\triangle BPC$ 是否全等？ 如果全等，请求出点 $Q$ 的运动速度；如果不全等，请说明理由。

#+begin_src latex
\begin{solution}[1in]
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 阶段1
*** 填空 8
当整数 $x$ = \fillin[2] 时，$\sqrt{x^{5 - x^{2}}}$ 是最简二次根式.

\begin{solution}
  \[
    \begin{cases}
      5 - x^{2} = 1 \\
      x > 0
    \end{cases}
    \begin{aligned}
      & x^2 = 4 \\
      & x = \pm 2
    \end{aligned}
    \therefore x = 2
  \]
\end{solution}

*** 填空 14
若正比例函数图像上的点到x轴的距离与到y轴距离的比为2:3,则函数的解析式为 \fillin[ $y = \frac{2}{3}x$ 或 $y=-\frac{2}{3}x$ ]

*** 填空 16                                                       :no_answer:
如图，点 $A_{1} (2,2)$ 在直线 $y=x$ 上，过点 $A_{1}$ 作 $A_{1}B_{1} \parallel y$ 轴交直线 $y=\frac{1}{2}x$ 于点 $B_{1}$ ，
以点 $A_{1}$ 为直角顶点， $A_{1}B_{1}$ 为直角边在 $A_{1}B_{1}$ 的右侧作等腰直角 $\triangle A_{1}B_{1}C_{1}$,
再过点 $C_{1}$ 作 $A_{2}B_{2} \parallel y$ 轴，分别交直线 $y=x$ 和 $y=\frac{1}{2}x$ 于 $A_{2}$，$B_{2}$ 两点，
以点 $A_{2}$ 为直角顶点，$A_{2}B_{2}$ 为直角边在 $A_{2}B_{2}$ 的右侧作等腰直角 $\triangle A_{2}B_{2}C_{2}$ ..,
按此规律进行下去，则等腰直角 $\triangle A_{m}B_{m}C_{m}$ 的面积为 \fillin[] . （用含正整数n的代数式表示）

#+begin_src latex
\begin{tikzpicture}
  \draw[->](-1,0)--(4.7,0) node at (5,0){$x$};
  \draw[->](0,-1)--(0,2.7) node at (0,3){$y$};

  \draw[domain=-0.5:2.5,name path = Fn1] plot(\x,\x) node at (2.7,2.7){$y=x$};
  \draw[domain=-0.5:3.7,name path = Fn2] plot(\x,0.5*\x) node at (4,2){$y=\frac{1}{2}x$};

  %三角形1
  \path[name path=l1] (0.8,0) --+ (0, 2.7);
  \fill[name intersections={of=l1 and Fn1,by=A1},
        name intersections={of=l1 and Fn2,by=B1}];
  \coordinate (C1) at ($ (A1)!1!90:(B1) $);
  \draw[line width=.5pt]  (A1) -- (B1) -- (C1) -- cycle;

  \foreach \i/\angle in {A1/90,B1/-90,C1/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  %三角形2
  \path[name path=l2] ($(C1) - (0, 3)$) -- ($(C1) + (0, 3)$);
  \fill[name intersections={of=l2 and Fn1,by=A2},
        name intersections={of=l2 and Fn2,by=B2}];
  \coordinate (C2) at ($ (A2)!1!90:(B2) $);
  \draw[line width=.5pt]  (A2) -- (B2) -- (C2) -- cycle;

  \foreach \i/\angle in {A2/90,B2/-90,C2/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  %三角形3
  \path[name path=l3] ($(C2) - (0, 3)$) -- ($(C2) + (0, 3)$);
  \fill[name intersections={of=l3 and Fn1,by=A3},
        name intersections={of=l3 and Fn2,by=B3}];
  \coordinate (C3) at ($ (A3)!1!90:(B3) $);
  \draw[line width=.5pt]  (A3) -- (B3) -- (C3) -- cycle;

  \foreach \i/\angle in {A3/90,B3/-90,C3/30} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }

  \node[draw] at ($(C3) + (0.8,0.8)$) {....};
\end{tikzpicture}
#+end_src

*** 计算和简答 17
\[\frac{2}{b} \sqrt{ab^{5}} \times (-\frac{3}{2}\sqrt{a^{3}b} \times 3\sqrt{\frac{a}{b}} \quad (a<0,b<0)\]

#+begin_src latex
\begin{solution}[1in]
  \[
    \begin{aligned}
    \mbox{原式} &= \frac{2 \times -3 \times 3}{b \times 2 } \sqrt{ ab^{5} \times a^{3}b \times \frac{a}{b} } \\
               &= - \frac{9}{b} \sqrt{a^{5}b^{5}} \\
               &= - \sqrt{9a^{2}b^{2}}{b} \sqrt{ab} \\
               &= - 9a^{2}b \sqrt{ab}
    \end{aligned}
  \]
\end{solution}
#+end_src

*** 计算和简答 21
若关于 $x$ 的一元二次方程 $(2m-1)x^{2} - 2 \sqrt{m}x + 1 = 0$ 有两个不相等的实数根。

#+LATEX: \begin{parts}
\epart 求 $m^{2}$ 的取值范围；

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
    & \begin{cases}
      2m - 1 \neq 0 \\
      \Delta > 0
      \end{cases} \\
    & \begin{aligned}
      \Delta &= 4m - 8m + 4 \\
             &= 4 - 4m
    \end{aligned} \\
    & \because \Delta > 0 \\
    & \begin{aligned} 
      \therefore 4 - 4m &> 0 \\
            4m &< 4 \\
             m &< 1
     \end{aligned} \\
    & \therefore 0 \leq m \le 1 \mbox{且} m \neq \frac{1}{2} \\
    & \mbox{答：} \quad 0 \leq m \le 1 \mbox{且}  m \neq \frac{1}{2} \mbox{时，原方程有两个不想等的实数根}
   \end{aligned}
\]
\end{solution}
#+end_src

\epart 当 $m + \frac{1}{m}=11$ 时，求 $\sqrt{m} - \frac{1}{\sqrt{m}}$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
     ( \sqrt{m} - \frac{1}{ \sqrt{m} } )^{2} &= m + \frac{1}{m} - 2 \\
     \mbox{当} m + \frac{1}{m} &= 11 \mbox{时} \\
     (\sqrt{m} - \frac{1}{\sqrt{m}}) ^{2} &= 11 - 2 \\
                                          &= 9 \\
      \sqrt{m} - \frac{1}{\sqrt{m}} &= \pm 3 \\
      \therefore \sqrt{m} - \frac{1}{ \sqrt{m} } = 3 \mbox{或} -3
   \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 计算和简答 22
已知方程 $x^{2} + 2(a+1)x + 3a^{2} + 4ab + 4b^{2} + 2 = 0$ 有2个相等的实数根，求 $a$ , $b$ 的值

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
     & \begin{aligned}
       \Delta &= (2(a+1))^{2} - 4(3a^{2} + 4ab + 4b^{2} + 2) \\
              &= 4a^{2} + 4 + 8a - 12a^{2} - 16ab - 16b^{2} - 8 \\
              &= -8a^{2} - 4 + 8a - 16ab - 16b^{2} \\
              &= -(4a^{2} - 8a + 4) - (4a^{2} + 16ab + 16b^{2}) \\
              &= - (2a - 2)^{2} - (2a + 4b)^{2}
     \end{aligned} \\
     & \therefore \Delta = 0 \\
     & \begin{cases}
          2a - 2 = 0 \\
          2a + 4b = 0
     \end{cases} \\
     & \mbox{解得：} \quad a = 1 \quad b = - \frac{1}{2} \\
     & \mbox{答：} a \mbox{为} 1 , \quad b \mbox{为} - \frac{1}{2}
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 24
已知 $\triangle ABC$ 中，$\angle ACB = 90 \degree$ , $AC=BC$ , 点 $D$ 在线段 $BC$ 上，联结 $AD$ , 过 $A$ 作 $AE  AD$,
且 $AE=AD$ , 联结 $BE$ , 交 $AC$ 于 $F$ , 联结 $DE$ . 猜想 $BD$ 和 $CF$ 有何数量关系，并加以证明

#+name: picture
#+begin_src latex
\begin{tikzpicture}
  \coordinate (B) at (0, 0);
  \coordinate (A) at (4, 4);
  \coordinate (C) at (4, 0);

  \coordinate (D) at ($ (B)!.6!(C) $);
  \coordinate (E) at ($ (A)!1!90:(D) $);
  \coordinate (F) at (intersection of B--E and A--C);

  \draw[line width=.5pt] 
    (A) -- (B) -- (C) -- cycle
    (A) -- (E) -- (D) -- cycle
    (B) -- (E);

  \foreach \i/\angle in {A/90, B/180, C/0, D/-90, E/0, F/-30 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}
#+end_src

#+name: solution
#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
   & \triangle ACD \cong \triangle AGE 
     \Rightarrow 
     \begin{cases}
        AC = EG = BC \\
        CD = AG
     \end{cases} \\
   & \Rightarrow \triangle FGE \cong \triangle FCB
     \Rightarrow GF = FC \\
   & BC = BD + CD \\
   & AC = GF + FC + AG \\
   & \therefore BD = GF + FC = 2CF
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 25
已知直线 $y=kx$ 过点 $(- \frac{1}{2},3)$ , $A$ 是直线 $y=kx$ 上一点，若过点 $A$ 向 $x$ 轴引垂线，垂足为 $B$ , 
且 $S_{\triangle AOB}=5$ , 求点 $B$ 的坐标。

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
    & \because \begin{aligned}
      & y = kx \quad (k \neq 0) \mbox{过点} ( - \frac{1}{2}, 3) \\
      & \mbox{当} y = 3 , x= - \frac{1}{2} \mbox{时} \\
      & k = -6 \\
      & y = -6x \\
      \end{aligned} \\
    & \because S_{\triangle AOB} = 5 \\
    & \therefore \begin{aligned}
        6 x^{2} &= 10 \\
          x^{2} &= \frac{5}{3} \\
              x &= \pm \frac{ \sqrt{5} }{ \sqrt{3} } \\
              x &= \pm \frac{ \sqrt{15} } { 3 }
      \end{aligned} \\
    B \mbox{的坐标为} (\frac{ \sqrt{15} }{3}, 0) \mbox{或} (- \frac{ \sqrt{15} }{3}, 0) 
   \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 27
如图，长方形 $OABC$ 的边长，$BC=4$ ,  $AB=2$

#+begin_src latex
\begin{tikzpicture}
  \tikzset{
    dot/.style={
      circle, fill=black, inner sep=1pt, outer sep=0pt
    },
    dot label/.style={
      circle, inner sep=0pt, outer sep=1pt
    },
  }

  \draw[->](-1,0)--(5,0);
  \draw[->](0,-1)--(0,3);

  \coordinate (A) at (4, 0);
  \coordinate (C) at (0, 2);
  \coordinate (B) at (4, 2);
  \coordinate (D) at (0, 0);
  \coordinate (P) at ($ (A)!.6!(B) $);

  % \draw[->](0,-1)--(0,3);

  \draw[line width=.5pt] 
    (C) -- (B)
    (A) -- (B)
    ($ (D)!-.2!(P) $) -- ($ (D)!1.2!(P) $)
    ;

  \foreach \i/\angle in {A/-90, B/90, C/60, D/120, P/0 } {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
  }
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\epart 直线 $y=kx \quad (k \neq 0)$ 交边 $AB$ 于点 $P$ , 求 $k$ 的取值范围；

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
   & \mbox{当} x = 4 \mbox{时} \\
   & y = 4k \\
   & \because P \mbox{在} BA \mbox{之间} \\
   & \therefore 0 \leq 4k \leq 2 \\
   & \because k \neq 0 \\
   & \therefore 0 < k < \frac{1}{2}
   \end{aligned}
\]
\end{solution}
#+end_src

\epart 直线 $y=kx \quad (k \neq 0)$ 是否可能将长方形 $OABC$ 的面积分成 2:3 两部分？若能，求出 $k$ 的值，若不能，说明理由。

#+begin_src latex
\begin{solution}[1in]
\[
   \begin{aligned}
     & \begin{aligned}
          S_{\Box}DABC &= ab \\
                       &= 8
       \end{aligned} \\
     & \begin{aligned}
       1. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDA = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & x = 4 \\
          & \therefore y1 = \frac{8}{5} \quad y2 = \frac{12}{5} \\
          & k1 = \frac{2}{5} \quad k2=\frac{3}{5} \\
       2. & P \mbox{在} BC \mbox{上} \\
          & S_{\triangle} PDC = \frac{16}{5} \mbox{或} \frac{24}{5} \\
          & y = 0 \\
          & \therefore X_{1} = \frac{15}{5} \quad x_{2} = frac{24}{5} \\
          & k4 = \frac{5}{8}
       \end{aligned} \\
     & \mbox{综上所述} \mbox{当} k = \frac{5}{8} \mbox{或} \frac{2}{5} \mbox{或} \frac{3}{5} \mbox{时，可以}
   \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 期中考试
*** 选择题 4
已知关于 $x$ 的方程 $(x+1)^{2} + a(x+1)+2=0$ 的两个实数根为 $m$ , $n$ 
则关于 $y$ 的方程 $2y^{2} + ay + 1 = 0$ 的根的情况是 \fillin

\begin{oneparchoices}
\choice $m+1$ , $n+1$
\choice $m-1$ , $n-1$
\choice $\frac{1}{m + 1}$ , $\frac{1}{n + 1}$
\choice $\frac{1}{m - 1}$ , $\frac{1}{n - 1}$
\end{oneparchoices}

*** 填空题 18                                                     :no_answer:
已知 $a$ , $b$ 是实数，且$(\sqrt{1+a^{2}} + a)(\sqrt{1+b^{2}}+b)=1$ , 问 $a$ , $b$ 之间有怎样的关系： \fillin[]

* 专项练习
** 正比例函数和反比例函数
*** 填空 1
在问题研究过程中，可以取不同数值的量叫 \fillin[自变量]。
保持数值不变的量叫做 \fillin[常量]。
表达两个变量之间依赖关系的数学式子称为 \fillin[函数解析式]。

*** 填空 9
函数有三种表示法，分别为 \fillin[图像法] ， \fillin[列表发] ， \fillin[解析法] 。

*** 填空 21
$y$ 与 $3x$ 成正比例，当 $x=8$ 时，$y=-12$ ,则 $y$ 与 $x$ 的函数解析式为 \fillin[ $y=-\frac{3}{2}x$ ]。

*** 填空 25
下列函数中，$y$ 随 $x$ 的增大而减少的函数是 \fillin[]

#+begin_src latex
\begin{oneparchoices}
  \choice $y=2x$
  \choice $y=\frac{1}{x}$
  \choice $y=- \frac{1}{x}$
  \correctchoice $y=\frac{2}{x} (x > 0)$
\end{oneparchoices}
#+end_src

*** 填空题 26
甲、乙两地相距 $100$ 千米，某人开车从甲地到乙地，那么它的速度 $v$ (千米／小时）与时间 $t$ (时）之间的函数关系用图象表示大致为 \fillin[D]

#+name: pic.正比例函数和反比例函数.25.base
#+begin_src latex :noweb yes :exports none
\draw[->](-1,0)--(1,0) node at (1,-0.2){$t$};
\draw[->](0,-1)--(0,1) node at (-0.2,1){$v$};
\draw node at (0.2, -0.2){$O$};
#+end_src

#+begin_src latex :noweb yes
\begin{oneparchoices}
\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-0.8:0.8] plot(\x,\x);
\end{tikzpicture}

\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=0:0.8] plot(\x,\x);
\end{tikzpicture}

\choice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-1/0.8:-0.8] plot(\x,{1/\x});
\end{tikzpicture}

\correctchoice
\begin{tikzpicture}
<<pic.正比例函数和反比例函数.25.base>>
\draw[domain=-1/0.8:-0.8] plot(\x,{1/\x});
\draw[domain=1/0.8:0.8] plot(\x,{1/\x});
\end{tikzpicture}

\end{oneparchoices}
#+end_src

*** 填空题 27
如果点 $A(x1,y1)$ 、$B(x2,y2)$ 在反比例函数 $y=\frac{k}{x} (k<0)$ 的图象上，
如果 $x_1 > x_2 > 0$ 则 $y_{1}$ 与 $y_{2}$ ,的大小关系是 \fillin[A]

#+begin_src latex
\begin{oneparchoices}
\correctchoice $y_{1} > y_{2}$
\choice $y_{1} < y_{2}$
\choice $y_{1} = y_{2}$
\choice 不能确定
\end{oneparchoices}
#+end_src

*** 问答题 29                                                         :error:
已知 $y = y_1 + y_2$ , $y_1$ 与 $x^2$ 成正比例， $y_2$ 与 $x-1$ 成反比例，当 $x=-1$ 时，$y=3$ ； 当 $x=2$ 时，$y=-3$ ，

#+LATEX: \begin{parts}
\part 求 $y$ 与 $x$ 之间的函数关系式；

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \mbox{设正比例函数解析式为} y_{1}=k_{1}x^{2} \quad (k_{1} \neq 0) \\
    & \mbox{反比例函数解析式为} y_{2}=\frac{k_{2}}{x - 1} \quad (k_{2} \neq 0) \\
    & \mbox{当} x = -1 \mbox{时} , y = 3 \\
    & \Rightarrow 3 = k_{1} - \frac{k_{2}}{2} \\
    & \mbox{当} x = 2 \mbox{时} , y = -3 \\
    & \Rightarrow -3 = 4k_{1} + k_{2} \\
    & \mbox{解得} k_{1} = \frac{1}{2} \quad k_{2} = -5 \\
    & \therefore y = \frac{x^{2}}{2} - \frac{5}{x - 1}
  \end{aligned}
\]
\end{solution}
#+end_src

\part 当 $x = \sqrt{2}$ 时，求 $y$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \mbox{当} x = \sqrt{2} \mbox{时} \\
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 问答题 31                                                     :no_answer:
如图，直线 $l$ 交 $x$ 轴、$y$ 轴与点 $A$ 、$B$ ，与反比例函数额图像交于 $C$ 、 $D$ 两点，如果 $A(2,0)$ ，
点 $C$ 、$D$ 分别在一、三象限，且 $OA = OB = AC = BD$ ， 求反比例函数的解析式。

#+begin_src latex
\begin{tikzpicture}[scale=0.6]
\draw[->](-5,0)--(5,0) node at (5,-0.5){$x$};
\draw[->](0,-5)--(0,5) node at (-0.5,5){$y$};

\draw[domain=1/0.25:0.25, name path=F1] plot(\x,{1/\x});
\draw[domain=-1/0.25:-0.25, name path=F2] plot(\x,{1/\x});

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 0);
\coordinate (B) at (0, -2);

\draw[-,name path=line]($(A)!2!(B)$)--($(B)!2!(A)$) ;

\fill[name intersections={of=F1 and line,by=C},
      name intersections={of=F2 and line,by=D}];

\foreach \i/\angle in {O/-145,A/-90,B/0,C/90,D/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 33
如图，在 $\triangle AOB$ 中， $AB=OB$ ,点 $B$ 在双曲线上，点 $A$ 的坐标为 $(2,0)$ , $S_{\triangle ABO}=4$ ,
求点 $B$ 所在双曲线的函数解析式。

#+begin_src latex
\begin{tikzpicture}
\draw[->](-1,0)--(2.5,0) node at (2.5,-0.5){$x$};
\draw[->](0,-2.5)--(0,0.5) node at (-0.5,0.5){$y$};

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 0);

\draw[domain=1/0.5:0.5, name path=F1] plot(\x,{-1/\x});

\path[name path=line] ($(O)!.5!(A)$) --+ (0,-2.5);
\fill[name intersections={of=F1 and line,by=B}];

\draw[-] (O) -- (B) -- (A);

\foreach \i/\angle in {O/-145,A/-90,B/-45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \because AB = OB \\
    & \therefore OE = OA = 1 \\
    & S_{\triangle AOB} = \frac{1}{2} \times OA \times BC = 4 \\
    & \therefore BC = 4 \\
    & \therefore y = \frac{4}{x}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 36                                                     :no_answer:
已知双曲线上两点 $A(2,4)$ , $C(4,2)$ , 且 $AB \perp OB$ , $CD \ perp OD$ ,

#+begin_src latex
\begin{tikzpicture}[scale=0.5]
\draw[->](-1,0)--(9,0) node at (9,-0.25){$x$};
\draw[->](0,-1)--(0,9) node at (-0.25,9){$y$};

\coordinate (O) at (0, 0);
\coordinate (A) at (2, 4);
\coordinate (C) at (4, 2);
\coordinate (B) at ($(O)!(A)!($(O) + (10,0)$)$);
\coordinate (D) at ($(O)!(C)!($(O) + (10,0)$)$);
\coordinate (E) at (intersection of A--B and O--C);

\draw[domain=1:8, name path=F1] plot(\x,{8/\x});
\draw[-]
  (O) -- (A) -- (B)
  (O) -- (C) -- (D);

\foreach \i/\angle in {O/-145,A/-90,B/-90,C/-45,D/-90,E/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\part
双曲线的函数解析式；

#+begin_src latex
\begin{solution}[.5in]
$$y=\frac{8}{x}$$
\end{solution}
#+end_src

\part
$\triangle OAB$ 的面积；

#+begin_src latex
\begin{solution}[.5in]
\[ \S_{\triangle OAB} = \frac{|k|}{2} = \frac{8}{2} = 4 \]
\end{solution}
#+end_src

\part
$\triangle OAC$ 的面积；

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \because S_{\triangle AOB} = S_{\triangle OCD} \\
    & \therefore S_{\triangle AOE} = S_{ECDB} \\
    & \therefore S_{\triangle AOC} = S_{ABDC} \\
    & S_{ABDC} = S_{\triangle AOB} \frac{(2 + 4)2}{2} = 6
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 一元二次方程根与系数的关系
*** 填空1
    :PROPERTIES:
    :ERROR:    1
    :END:

若 $2x(x+3)=1$ 的两根分别为 $x_{1}$ , $x_{2}$ 则有 $x_{1} + x_{2} =$ \fillin[-3] , $x_{1}x_{2}=$ \fillin[ $-\frac{1}{2}$ ]
${x_1}^2 x_2 + x_1 {x_2}^{2}=$ \fillin[ $\frac{3}{2}$ ] , 
${x_1}^2 + {x_2}^2=$ \fillin[10] , 
$\frac{4}{x_1} + \frac{4}{x_2}=$ \fillin[ $-\frac{2}{3}$ ]

*** 填空2
已知：关于 $x$ 的方程 $x^2-(m+1)x+m-2=0$ ,
1. 若两根的和为 $3$ , 则 $m=$ \fillin[2]
2. 若两根互为相反数, 则 $m=$ \fillin[-1]
3. 若两根互为倒数, 则 $m=$ \fillin[3]
4. 若有一个根为 $0$ , 则 $m=$ \fillin[2]

*** 填空3
已知实数 $m$ 、$n$ 满足 $m^{2} + m - 4 = 0$ , $\frac{1}{n^{2}} + \frac{1}{n} - 4 = 0$ 且 $m \neq \frac{1}{n}$ , 
则 $m+\frac{1}{n}=$ \fillin[-1] 。

#+begin_src latex
\begin{solution}
\[
\begin{aligned}
m , \frac{1}{n} \mbox{为} x^2 + x - 4 \mbox{的解} \\
m + \frac{1}{n} = - \frac{b}{a} = -1
\end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 4
已知 $a$ , $b$ 是方程 $x^2 + x - 2009 = 0$ 的两个实数根，求 $a^2 + 2a + b$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  & \begin{aligned}
      a + b &= -1 \\
      ab &= - 2009 \\
      a^2 &= 2009 - a \\
     \end{aligned} \\
  & \begin{aligned} 
       \mbox{原式} &= 2009 + a + b \\
                  &= 2009 - 1 \\
                  &= 2008
    \end{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 5
已知 $3m^{2} - 2m - 5 = 0$ , $5n^2 + 2n - 3 = 0$ , 其中 $m \cdot n$ 为实数，求 $|m - \frac{1}{n}|$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  & \begin{aligned}
      5n^2 + 2n - 3 &= 0 \\
       5 + 2 \frac{1}{n} - 3 \frac{1}{n^2} &= 0 \\
       3 \frac{1}{n^2} - 2 \frac{1}{n} - 5 &= 0 \\
    \end{aligned} \\
  \therefore & m \mbox{和} \frac{1}{n} \mbox{是方程} 3x^2 - 2x - 5 = 0 \mbox{的两个根} \\
  \therefore & \begin{cases}
                  m + \frac{1}{n} = \frac{2}{3} \\
                  m \cdot \frac{1}{n} = -\frac{5}{3}
               \end{cases} \\
  \therefore & \begin{cases} 
      \textcircled{1} m \neq \frac{1}{n} \\
      \begin{aligned}
      \qquad | m - \frac{1}{n} | &= \sqrt{(m + \frac{1}{n})^{2} - 4 m \cdot \frac{1}{n} } \\
                                 &= \sqrt{\frac{4}{9} + \frac{20}{3}} \\
                                 &= \sqrt{\frac{64}{9}} \\
                                 &= \frac{8}{3}
      \end{aligned} \\
      \textcircled{2} m = \frac{1}{n} \\
      \begin{aligned}
      \qquad |m - \frac{1}{n}| = 0
      \end{aligned}
    \end{cases}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 6
已知实数 $m$ 、$n$ 满足 $m^{2} - 7m + 2 = 0$ , $n^{2} - 7n + 2 = 0$ , 求 $\frac{n}{m} + \frac{m}{n}$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & x^{2} - 7m + 2 = 0
      \qquad \Rightarrow \qquad
      \begin{cases}
        & mn = 2 \\
        & m + n = 7
      \end{cases} \\
    & \begin{aligned}
        \mbox{原式} &= \frac{(m + n)^2}{mn} - 2 \\
                   &= \frac{49}{2} - 2 \\
                   &= \frac{45}{2}
      \end{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 7
已知实数 $m$ 、$n$ , 满足 $19m^{2} + 99m + 1 = 0$ , $n^{2} + 99n + 19 = 0$ , $mn \neq 1$ 求 $\frac{mn+4m+1}{n}$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  & \begin{aligned}
      n^{2} + 99n + 19 &= 0 \\
      19 \frac{1}{n^{2}} + 99 \frac{1}{n} + 1 &= 0 \\
      \mbox{令：} x = \frac{1}{n} \\
      19 x^{2} + 99x + 1 &= 0 \\
    \end{aligned} \\
   & \begin{aligned}
       \mbox{原式} &= m + \frac{1}{n} + 4 \frac{m}{n} \\
                  &= - \frac{99}{19} + \frac{4}{19} \\
                  &= -5
     \end{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 8
若 $m$ 、$n$ 是方程 $x^2 + 2x - 7 = 0$ 的两个实数根，求：$m^3 - 5n^2 + n + 76$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \because m n \mbox{是方程} x^2 + 2x - 7 = 0 \mbox{的两个实数根} \\
    & \therefore \begin{cases}
                    m^2 = 7 - 2m
                    n^2 = 7 - 2n
                 \end{cases} \\
    & \begin{aligned}
      m^{2} &= 7 - 2m \\
      m^{3} &= 7m - 2m^{2} \\
            &= 7m - 14 + 4m
      \end{aligned} \\
    & \begin{aligned}
        \mbox{原式} &= 11m - 14 - 35 + 10n + 76 + n \\
                   &= 11(m + n) + 27 \\
                   &= 5 
      \end{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 11
已知关于 $x$ 的方程 $x^{2} - (k+1)x + \frac{1}{4}k^{2} + 1 = 0$ .

#+LATEX: \begin{parts}
\part
$k$ 取何值时，方程存在两个正实数根？

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \begin{cases}
        x_{1} x_{2} > 0 \\
        x_{1} + x_{2} > 0
      \end{cases} \\
    & \frac{1}{4} k^2 > 0 \Rightarrow k^2 > -4 \\
    & k + 1 > 0 \Rightarrow k > -1 \\
    \therefore & k > -1 \mbox{时,方程有两个实数根}
  \end{aligned}
\]
\end{solution}
#+end_src

\part 若方程的两根是一个矩形相邻两边的长，当矩形的对角线长是 $\sqrt{5}$ 时，求 $K$ 的值。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & x_1^2 + x_2^2 = 5 \\
    \Rightarrow & (x_1 + x_2)^2 - 2 x_1 x_2 = 5 \\
    \Rightarrow & (k + 1)^2 - \frac{1}{2} k^{2} - 2 = 5 \\
                & \frac{1}{2} k^{2} - 1 + 2k = 5 \\
                & k^{2} + 4k - 12 = 0 \\
    \Rightarrow & k_1 = 2 \qquad k_2 = -6
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 解答题 10(2)
已知关于 $x$ 的方程 $(k-1)x^{2} + (2k-3)x + k + 1 = 0$ 有两个不相等的实数根 $x_{1}$ , $x_{2}$ ·

#+LATEX: \begin{parts}
\part 求 $k$ 的取值范围；

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  & \begin{cases}
      k \neq 1 \\
      \Delta > 0
    \end{cases} \\
  & \begin{aligned}
    \Delta &= (2k - 3)^{2} - 4(k^{2} - 1) \\
           &= 4k^{2} + 9 - 12k - 4k^{2} + 4 \\
           &= 13 - 12k
    \end{aligned} \\
  & \therefore
    \begin{aligned}
      & 13 - 12k > 0
      & k < \frac{13}{12}
    \end{aligned} \\
  & \mbox{答：} k < \frac{13}{12} \quad \mbox{且} \quad k \neq 1
  \end{aligned}
\]
\end{solution}
#+end_src

\part 是否存在实数 $k$ ,使方程的两实根互为相反数？如果存在，求出 $k$ 的值；如果不存在，请你说明理由。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & - \frac{2k-3}{k-1} = 0 \\
    & 2k - 3 = 0 \\
    & k = \frac{2}{3}
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 垂直品分线于角平分线
*** 填空题 3
已知在 $\triangle ABC$ 中, $AB=AC$ , $\triangle BAC = 120 \degree$ , 
$DE$ 垂直平分 $AB$ , 且交 $CA$ 的延长线于 $D$ , 则 $\angle DBC$ 的度数为 \fillin [ $90 \degree$ ]

*** 填空题 8
如图，在 $\triangle ABC$ 中， $AC$ 的垂直平分线交 $AC$ 于 $E$ , 交 $BC$ 于 $D$ , 
$\triangle ABD$ 的周长为 $12cm$ , $AC=5cm$,则 $\triangle ABC$ 的周长为 \fillin[17] cm.

#+begin_src latex
\begin{tikzpicture}

\coordinate (A) at (0, 3);
\coordinate (B) at (-1, 0);
\coordinate (C) at (1, 0);
\coordinate (E) at ($(A)!(B)!(C)$);
\coordinate (D) at ($(A)!(E)!(B)$);

\draw (A) -- (B) -- (C) -- cycle
(B) -- (E)
(E) -- (D)
;

\foreach \i/\angle in {A/90,B/-135,C/-45,E/45,D/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

*** 填空题 10
在 $\triangle ABC$ 中， $AB=AC$ , $\triangle BAC = 120 \degree$ , $AC$ 的垂直平分线交 $BC$ 于 $D$ , 交 $AC$ 于 $E$ ,
若 $DE=5cm$ , 则 $BC$ 的长度为 \fillin[30] cm.

*** 填空题 13
如图， 在锐角三角形 $ABC$ 中, $\angle BAC=50 \degree$ , $AC$ 、 $BC$ 的垂直平分线交于点 $O$ ， 
则 $\angle BOC$ 的度数为 \fillin[ $100 \degree$ ]

*** 问答题 15
如图, 在 $\triangle OBC = \triangle OCB$ , $\triangle AOB = \triangle AOC$ ,
求证: $AD$ 是 $BC$ 的垂直平分线。

#+begin_src latex
\begin{tikzpicture}

\coordinate (A) at (0, 4);
\coordinate (B) at (-1, 0);
\coordinate (C) at (1, 0);
\coordinate (E) at ($(B)!(A)!(C)$);
\coordinate (O) at ($(A)!.7!(E)$);

\draw (A) -- (B) -- (C) -- cycle
(A) -- (E)
(B) -- (O) -- (C)
;

\foreach \i/\angle in {A/90,B/-135,C/-45,E/-90,O/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
   \begin{aligned}
   & \mbox {延长} AO \mbox{交} BC \mbox{于} E \\
   & \because \angle OBC = \angle OCB \\
   & \therefore BO = OC \\
   & \because \angle AOD = \angle AOC \\
   & \therefore \angle BOE = \angle COE \\
   \mbox{又} & \because BO = OC \\
   & \therefore BE = CE \\
   & \therefore \triangle OBC \mbox{为等腰三角形}
   \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 16                                                     :no_answer:
已知如图, $CD$ 是 $RT \triangle ABC$ 斜边上的高， $\triangle A$ 的平分线交 $CD$ 于 $H$ , 交 $\angle BCD$ 的平分线于 $G$ ,
求证： $HF \pxx BC$ .

#+begin_src latex
\begin{tikzpicture}

\coordinate (A) at (0, 0);
\coordinate (B) at (4, 0);
\coordinate (C) at ($(B)!(A)!($(B)!1!-60:(A)$)$);
\coordinate (D) at ($(A)!(C)!(B)$);

% 求角 CAB 的平分线的交点
\path (A) [name path=CircleA] circle (1); 
\path [name path=a1] (A) -- (B);
\path [name path=a2] (A) -- (C);
\fill[name intersections={of=CircleA and a1,by=A1},
      name intersections={of=CircleA and a2,by=A2}];
\coordinate (E) at (intersection of A--$(A)!5!($(A1)!.5!(A2)$)$ and B--C);
\coordinate (H) at (intersection of A--E and C--D);

% 求角 DCB 的平分线的交点
\path (C) [name path=CircleC] circle (1); 
\path [name path=c1] (C) -- (D);
\path [name path=c2] (C) -- (B);
\fill[name intersections={of=CircleC and c1,by=C1},
      name intersections={of=CircleC and c2,by=C2}];

\coordinate (F) at (intersection of C--$(C)!5!($(C1)!.5!(C2)$)$ and B--A);
\coordinate (G) at (intersection of C--F and A--E);

% 画线
\draw (A) -- (B) -- (C) -- cycle
(C) -- (D)
(A) -- (E)
(C) -- (F) -- (H)
;

% 标点
\foreach \i/\angle in {A/-135,B/-45,C/90,E/45,H/135,F/-90,G/-45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \angle A \mbox{的平分线，} \angle ADC = \angle ACE = 90 \degree \\
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 17                                                     :no_answer:
已知在 $RT \triangle ABC$ 中， $\angle BAC = 90 \degree$ , $AD$ 是斜边 $BC$ 上的高， $BF$ 平分 $\angle ABC$ , 
交 $AC$ 于点 $F$ 交 $AD$ 于点 $E$ , $EG \pxx BC$ 交 $AC$ 于点 $G$ , 求证 $AF=CG$

#+begin_src latex
\begin{tikzpicture}

\coordinate (B) at (0, 0);
\coordinate (C) at (4, 0);
\coordinate (A) at ($(C)!(B)!($(C)!1!-55:(B)$)$);
\coordinate (D) at ($(B)!(A)!(C)$);

% 求角 CAB 的平分线的交点
\path (B) [name path=CircleB] circle (1); 
\path [name path=a1] (B) -- (A);
\path [name path=a2] (B) -- (C);
\fill[name intersections={of=CircleB and a1,by=B1},
      name intersections={of=CircleB and a2,by=B2}];
\coordinate (F) at (intersection of B--$(B)!5!($(B1)!.5!(B2)$)$ and A--C);
\coordinate (E) at (intersection of B--F and A--D);

% 平行线
\coordinate (G) at (intersection of E--$($(E) - (B)$) + (C)$
                                 and A--C);

% 画线
\draw (A) -- (B) -- (C) -- cycle
(A) -- (D)
(B) -- (F)
(E) -- (G)
;

% 标点
\foreach \i/\angle in {A/-135,B/-45,C/90,D/45,E/135,F/45,G/45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 18                                                     :no_answer:
$AD$ 是等腰三角形 $ABC$ 底边上的高，$E$ , $F$ 为 $AD$ 上的两点， 且 $\angle ABE = \angle EBF = \angle FBC$ ,
连接 $CF$ 并延长交 $AB$ 于点 $G$.

#+begin_src latex
\begin{tikzpicture}

\coordinate (B) at (0, 0);
\coordinate (C) at (2.5, 0);
\coordinate (A) at (intersection of B--$(B)!2!69:(C)$
                                 and C--{$(C)!2!-69:(B)$});
\coordinate (D) at ($(B)!.5!(C)$);

\coordinate (E) at (intersection of B--$(B)!1!46:(C)$
                                 and A--D);

\coordinate (F) at (intersection of B--$(B)!1!23:(C)$
                                 and A--D);

\coordinate (G) at (intersection of C--$(C)!3!(F)$
                                 and A--B);

% 画线
\draw (A) -- (B) -- (C) -- cycle
(A) -- (D)
(C) -- (G)
(B) -- (E)
(B) -- (F)
(G) -- (E)
;

% 标点
\foreach \i/\angle in {A/90,B/-135,C/-45,D/-90,E/45,F/45,G/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\part 求证 $\triangle GBF$ 为等腰三角形

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

\part 求证 $GE \pxx BF$

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

* 复习卷
** 期中复习（几何）
*** 填空题 6
如图, 在 $\triangle ABC$ 中， $\angle C = 90 \degree$ , $E$ 为 $AB$ 的中点，且 $DE \perp AB$ 于 $F$ , 交 $BC$ 于点 $D$ ,
如果 $\angle CAD : \angle ADC = 3:2$ , 那么 $\angle BAC=$ \fillin[ $72 \degree$ ]

#+begin_src latex
\begin{tikzpicture}
\coordinate (A) at (0,2);
\coordinate (C) at (0,0);
\coordinate (B) at (5,0);
\coordinate (E) at ($(A)!.5!(B)$);
\coordinate (D) at (intersection of E--$(E)!1!90:(A)$ and B--C);

\draw[-] (A) -- (B) -- (C) -- cycle
($(E)!1.8!(D)$) -- ($(D)!1.8!(E)$)
(A) -- (D)
;

\foreach \i/\angle in {A/135,B/45,C/-135,D/-45,E/45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

*** 填空题 7
如图, $\mbox{等腰} \triangle ABC$ 的周长 $50cm$ , $AB$ 的垂直平分线交另一腰 $AC$ 于 $D$ , 
$\triangle BCD$ 的周长为 $36cm$ , 则底边 $BC=$ \fillin[ $22cm$ ]

#+begin_src latex
\begin{tikzpicture}
\coordinate (A) at (1.5,4);
\coordinate (B) at (0,0);
\coordinate (C) at (3,0);
\coordinate (M) at ($(A)!.5!(B)$);
\coordinate (D) at (intersection of M--$(M)!1!90:(A)$ and A--C);

\draw[-] (A) -- (B) -- (C) -- cycle
($(M)!1.8!(D)$) -- ($(D)!1.8!(M)$)
(B) -- (D)
;

\foreach \i/\angle in {A/135,B/45,C/-135,D/-45,M/135} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

*** 填空题 8
已知如图, 在 $\triangle ABC$ 中， $\angle C = 90 \degree$ , $AC=BC$ , 点 $D$ 在 $BC$ 上, $DE \perp AB$ ,
点 $E$ 为垂足, 且 $DE=DC$ ， 连接 $AD$ . 则 $\angle ADB=$ \fillin[ $112.5 \degree$ ]

#+begin_src latex
\begin{tikzpicture}
\coordinate (A) at (0,0);
\coordinate (B) at (4,0);
\coordinate (C) at (2,2);
\coordinate (D) at ($(C)!.45!(B)$);
\coordinate (E) at ($(A)!(D)!(B)$);

\draw[-] (A) -- (B) -- (C) -- cycle
(A) -- (D)
(D) -- (E)
;

\foreach \i/\angle in {A/-90,B/-45,C/90,D/45,E/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

*** 填空题 10
$Rt \triangle ABC$ 中，$\angle B = 90 \degree$ , $D$ 在 $BC$ 上，$DE \perp AC$ , 垂足为 $E$ , $BD=DE$ ; 
如 $\angle C=32 \degree$, $\angle ADE=$ \fillin[ $61 \degree$ ]

*** 填空题 11
一个三角形的两条边长分别为 $5$ 和 $3$ , 第三边的中线长为 $x$ , 则 $x$ 的取值范围是 \fillin[ $2 < 2x < 8 \Rightarrow 1 < x < 4$ ]

*** 选择题 1
下列四个命题的逆命题是假命题的是 \fillin[ C ]

\begin{choices}
\choice 直角三角形的两个锐角互余
\choice 等腰三角形的两个底角相等
\correctchoice 全等三角形的对应角相等
\choice 相等的两个角是对顶角
\end{choices}

*** 证明题 1
在四边形 $ABCD$ 中，$\angle BAD = \angle BCD$ , $\angle ABC$ 的平分线交直线 $AD$ 于点 $P$ ,
经过点 $A$ 与 $BP$ 垂直的直线交直线 $BC$ 下点 $Q$ . 求证： $PQ \pxx CD$

#+begin_src latex
\begin{tikzpicture}
\coordinate (R) at (0,0);
\coordinate (A) at (0,-2);
\coordinate (B) at (-3.5,0);
\coordinate (Q) at (0,2);
\coordinate (P) at (2.2,0);
\coordinate (C) at ($(B)!.78!(Q)$);
\coordinate (D) at ($(A)!.78!(P)$);

\draw[-] (A) -- (B) -- (Q) -- (P) -- cycle
(B) -- (P)
(A) -- (Q)
(C) -- (D)
;

\foreach \i/\angle in {A/-45,B/-135,C/90,D/-45,R/-135,P/-45,Q/90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}
\[
  \begin{aligned}
    & \begin{rcases}
      AQ \perp BP \\
      BP \mbox{平分} \angle ABC
    \end{rcases}  \\
    \Rightarrow & \angle BAQ = \angle BQA \\
    \Rightarrow & BA = BQ \\
    \Rightarrow & PQ = PA \\
    \Rightarrow & \angle PAQ = \angle PQA \\
    \Rightarrow & \angle BAD = \angle BQP \\
    \Rightarrow & CD \pxx PQ
  \end{aligned}
\]
\end{solution}
#+end_src

*** 证明2
如图，已知 $\triangle ABC$ 是等腰直角三角, $\angle ACB = 90 \degree$ , $\triangle ADB$ 是等边三角形，
点 $C$ 在 $\triangle ADB$ 内部, $DE \perp AC$ 交直线 $AC$ 于点 $E$ 。

#+begin_src latex
\begin{tikzpicture}
\coordinate (C) at (0,3.5);
\coordinate (A) at ($(C)!2cm!-135:($(C)+(1,0)$)$);
\coordinate (B) at ($(C)!2cm!-45:($(C)+(1,0)$)$);

\coordinate (D) at ($(C)+(0,1)$);
\coordinate (E) at ($(A)!(D)!(C)$);

\draw[-] (A) -- (B) -- (C) -- cycle
(A) -- (D) -- (B)
(D) -- (E) -- (C)
;

\foreach \i/\angle in {A/-45,B/-135,C/90,D/90,E/45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

#+LATEX: \begin{parts}
\part 求证： $DE=CE$

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
               & \mbox{延长} DC \mbox{交} AB \mbox{于} F \\
    \because   & AD = DB , AC = CB \\
    \therefore & D, C \mbox{在} AB \mbox{的垂直平分线上} \\
    \therefore & DC \mbox{垂直平分} AB \\
    \therefore & \angle ACF = \angle BCF \\
    \mbox{又}  & \angle ACB = 90 \degree \\
    \therefore & \angle DCE = \angle ACF = 45 \degree \\
    \because   & DE \perp AE \\
    \therefore & \angle EDC = \angle DCF = 45 \degree \\
    \therefore & DE = CE
  \end{aligned}
\]
\end{solution}
#+end_src

\part 若 $C$ 在 $\triangle ADB$ 外部， $DE=CE$ 的关系是否成立？如不成立，请说明理由，如成立请证明。

#+begin_src latex
\begin{solution}[1in]

\begin{tikzpicture}
\coordinate (C) at (0,3.5);
\coordinate (A) at ($(C)!2cm!-135:($(C)+(1,0)$)$);
\coordinate (B) at ($(C)!2cm!-45:($(C)+(1,0)$)$);

\coordinate (D) at ($(C)+(0,-4)$);
\coordinate (E) at ($(A)!(D)!(C)$);

\draw[-] (A) -- (B) -- (C) -- cycle
(A) -- (D) -- (B)
(D) -- (E) -- (C)
;

\foreach \i/\angle in {A/-45,B/-135,C/90,D/90,E/45} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}

\[
  \begin{aligned}
               & \mbox{延长} DC \mbox{交} AB \mbox{于} F \\
    \because   & AD = DB , AC = CB \\
    \therefore & D, C \mbox{在} AB \mbox{的垂直平分线上} \\
    \therefore & DC \mbox{垂直平分} AB \\
    \therefore & \angle ACF = \angle BCF \\
    \mbox{又}  & \angle ACB = 90 \degree \\
    \therefore & \angle DCE = \angle ACF = 45 \degree \\
    \because   & DE \perp AE \\
    \therefore & \angle EDC = \angle DCF = 45 \degree \\
    \therefore & DE = CE
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

* 周测
** 周测1
*** 选择题 5
等腰直角三角形 $ABC$ 位于第一象限，$AB=AC=2$ ,直角顶点 $A$ 在直线 $y=x$ 上，
其中 $A$ 点的横坐标为 $1$ ,且两条直角边 $AB$ 、 $AC$ 分别平行于 $x$ 轴、$y$ 轴，
若双曲线 $y= \frac{k}{x}(k \neq 0)$ 与 $\triangle ABC$ 有交点，
则k的取值范围是 \fillin

#+begin_src latex
\begin{tikzpicture}[scale=0.7]
\draw[->](-1,0)--(4.5,0) node at (5,0){$x$};
\draw[->](0,-1)--(0,4.5) node at (0,5){$y$};

\coordinate (A) at (1,1);
\coordinate (B) at (3,1);
\coordinate (C) at (1,3);

\draw[domain=-1:3] plot(\x,\x);
\draw (A) -- (B) -- (C) -- cycle;

\draw[domain=0.7:4.1] plot(\x,{2.5/\x});

\foreach \i/\angle in {A/120,B/-90,C/45} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
#+end_src

\begin{oneparchoices}
\choice $1 < k < 2$
\choice $1 \leq k \leq 3$
\correctchoice $1 \leq k \leq 4$
\choice $1 \leq k < 4$
\end{oneparchoices}

*** 填空题 6                                                      :no_answer:
实数范围内因式分解: $2x^2y^2 - 3xy - 1=$ \fillin[ ]

*** 填空题 11
设反比例函数 $y=-6x^{1}$ , 当 $-6 \leq x \leq -2$ 时，函数的最大值是 \fillin[3]

*** 简答题 17
解方程: $2x(x-2)=x^{2}-3$

#+begin_src latex
\begin{solution}[.5in]
\[
  \begin{aligned}
    & 2x^{2} - 4x = x^{2} - 3 \\
    & x^{2} - 4x + 3 = 0 \\
    & x - 3 = 0 \qquad x - 1 = 0 \\
    & x = 3 \qquad x = 1 \\
    \therefore & \mbox{方程的解为} x_{1} = 1 \quad x_{2} = 3
  \end{aligned}
\]
\end{solution}
#+end_src

*** 解答题 19                                                     :no_answer:
如图，四边形 $ABCD$ 中, $AB=CB$ , $\angle ABC = 60 \degree$ , $\angle ADC = 120 \degree$ , 
请你猜想线段 $DA$ 、 $DC$ 、 $BD$ 的数量关系? 并证明你的结论。

#+begin_src latex
\begin{tikzpicture}

\coordinate (A) at (0,0);
\coordinate (B) at ($(A)!1!-45:($(A)+(0,-2)$)$);
\coordinate (C) at ($(B)!1!-60:(A)$);
\coordinate (D) at (intersection of C--{$(C)!1!-90:(B)$}
                                and A--{$(A)!1!90:(B)$});

\draw (A) -- (B) -- (C) -- (D) -- cycle;

\foreach \i/\angle in {A/90,B/-180,C/-90,D/15} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
#+end_src

#+begin_src latex
\begin{solution}[.5in]
\end{solution}
#+end_src

*** 解答题 21                                                     :no_answer:
如图，在等腰直角三角形 $ABC$ 中，$O$ 是斜边 $AC$ 的中点，
$P$ 是斜边 $AC$ 上的一个动点，（不与 $A$ , $C$ 重合）
$D$ 为射线 $BC$ 上的一点，且 $PB=PD$ ,
过 $D$ 点作 $AC$ 边上的高 $DE$ .

#+begin_src latex
\begin{figure}[htbp]
\centering
\subfigure {
\begin{minipage}[b]{0.4\linewidth}
\centering
\begin{tikzpicture}[scale=1.5]

\coordinate (A) at (0,2);
\coordinate (B) at (0,0);
\coordinate (C) at (2,0);
\coordinate (O) at ($(A)!.5!(C)$);
\coordinate (P) at ($(A)!.3!(C)$);
\coordinate (D) at ($(B)!($(B)!2!(P)$)!(C)$);
\coordinate (E) at ($(A)!(D)!(C)$);

\draw (A) -- (B) -- (C) -- cycle
(B) -- (O)
(B) -- (P) -- (D) -- (E)
;

\foreach \i/\angle in {A/90,B/-180,C/-90,O/45,P/45,D/-90,E/45} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
\end{minipage}
}
\subfigure {
\begin{minipage}[b]{0.4\linewidth}
\centering
\begin{tikzpicture}[scale=1.5]

\coordinate (A) at (0,2);
\coordinate (B) at (0,0);
\coordinate (C) at (2,0);
\coordinate (O) at ($(A)!.5!(C)$);
\coordinate (P) at ($(A)!.7!(C)$);
\coordinate (D) at ($(B)!($(B)!2!(P)$)!(C)$);
\coordinate (E) at ($(A)!(D)!(C)$);

\draw (A) -- (B) -- (C) -- cycle
(B) -- (O)
(B) -- (P) -- (D) -- (E)
(E) -- (C)
(D) -- (C)
;

\foreach \i/\angle in {A/90,B/-180,C/-90,O/45,P/45,D/-90,E/-90} {
    \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
\end{minipage}
}
\end{figure}
#+end_src

#+LATEX: \begin{parts}
\part 探索当 $D$ 在线段 $BC$ 上或当 $D$ 在 $BC$ 延长线上时， $PE$ 与 $BO$ 分别有什么数量关系？说明理由；

#+begin_src latex
\begin{solution}[.5in]
\end{solution}
#+end_src

\part 设 $AC=8$ , $AP=x$ , $S_{\triangle PBD}=y$ , 求 $y$ 与 $x$ 之间的函数关系式，并写出自变量 $x$ 的取值范围:

#+begin_src latex
\begin{solution}[.5in]
\end{solution}
#+end_src

\part 是否存在这样的 $P$ 点，是的 $\triangle PBD$ 的面积是 $\triangle ABC$ 面积的 $\frac{3}{8}$ ?
如果存在，求出 $AP$ 的长；如果不存在，请说明理由。

#+begin_src latex
\begin{solution}[1in]
\end{solution}
#+end_src

#+LATEX: \end{parts}

** 周测2
*** 选择题6
如图，直线 $l_{1}$ , $l_{2}$ , $l_{3}$ , 表示三条相互交叉的公路，现要建一个货物中转站，要求它的三条公路的距离相等，则可供选择的地址有 \fillin

#+name: pic.周测2.6.base
#+begin_src latex :exports none
\coordinate (a) at (-1,0);
\coordinate (b) at (1,0);
\coordinate (c) at (0, -1.5);

\draw ($(b)!1.4!(a)$) -- ($(a)!1.4!(b)$) node at ($(a)!1.5!(b)$){$l_{1}$}
($(a)!1.4!(c)$) -- ($(c)!1.4!(a)$) node at ($(c)!1.5!(a)$){$l_{2}$}
($(b)!1.4!(c)$) -- ($(c)!1.4!(b)$) node at ($(c)!1.5!(b)$){$l_{3}$}
;
#+end_src

#+begin_src latex :noweb yes
\begin{tikzpicture}
<<pic.周测2.6.base>>
\end{tikzpicture}
#+end_src

\begin{oneparchoices}
\choice 一处
\choice 二处
\choice 三处
\correctchoice 四处
\end{oneparchoices}

#+begin_src latex :noweb yes
\begin{solution}
\centering
\begin{tikzpicture}
<<pic.周测2.6.base>>

\coordinate (A) at ($(c)!1.6!($(a)!.5!(b)$)$);
\draw[dashed]
 (A) -- ($(a)!(A)!(b)$)
 (A) -- ($(a)!(A)!(c)$)
 (A) -- ($(b)!(A)!(c)$)
;

\coordinate (B) at ($(b)!1.6!($(a)!.5!(c)$)$);
\draw[dashed]
 (B) -- ($(a)!(B)!(b)$)
 (B) -- ($(a)!(B)!(c)$)
 (B) -- ($(b)!(B)!(c)$)
;

\coordinate (C) at ($(a)!1.6!($(b)!.5!(c)$)$);
\draw[dashed]
 (C) -- ($(a)!(C)!(b)$)
 (C) -- ($(a)!(C)!(c)$)
 (C) -- ($(b)!(C)!(c)$)
;

\coordinate (D) at (0,-0.6);
\draw[dashed]
 (D) -- ($(a)!(D)!(b)$)
 (D) -- ($(a)!(D)!(c)$)
 (D) -- ($(b)!(D)!(c)$)
;

\foreach \i/\angle in {A/90,D/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
\end{solution}
#+end_src

*** 填空题 15
$\triangle ABC$ 中， $AB=AC$ , $MN$ 垂直平分 $AB$ 分别交 $AB$ 、 $BC$ 于点 $M$ 、 $N$ ,
如果 $\triangle ACN$ 是等腰三角形，则 $\angle B=$ \fillin[ $72 \degree$ 或 $36 \degree$ ]

*** 简答题 20
如图，已知 $A$ : $(-a,0)$ 、 $B$: $(a,0)$ , 点 $P$ 为第二象限内一动点，但始终保持 $PA=a$ , 
$\angle PAB$ 的角平分线 $AE$ 与线段 $PB$ 的垂直平分线 $CD$ 交于点 $D$ , 与 $PB$ 交于点 $E$ ,
作 $DF$ 垂直 $AB$ 于点 $F$ ,请求点 $D$ 的横坐标。

* 十每
** 十每
*** 问答题 1
如图， $\triangle ABC$ 是边长为 $4$ 的等边三角形， $\triangle BCD$ 是顶角 $\angle BCD=120 \degree$ 的等腰三角形，
以 $D$ 为定点做一个 $60 \degree$ 的角，角的两边交 $AB$ , $AC$ 于 $M$ 、 $N$ 两点，连 $MN$ ，
求 $\triangle AMN$ 的周长?

#+name: pic.十每.1.base
#+begin_src latex :exports none
\coordinate (B) at (0, 0);
\coordinate (C) at (2.5, 0);
\coordinate (A) at ($(B)!1!60:(C)$);

\coordinate (D) at (intersection of B--$(B)!2!-30:(C)$
                                 and C--{$(C)!2!30:(B)$});

\coordinate (M) at (intersection of D--$(D)!1!45:(A)$
                                 and A--B);

\coordinate (N) at (intersection of D--$(D)!2!-60:(M)$ and C--A);

% 画线
\draw (A) -- (B) -- (C) -- cycle
(B) -- (D) -- (C)
(D) -- (M) -- (N) -- cycle
;

% 标点
\foreach \i/\angle in {A/90,B/-135,C/-45,D/-90,M/135,N/0} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
#+end_src

#+begin_src latex :noweb yes
\begin{tikzpicture}
<<pic.十每.1.base>>
\end{tikzpicture}
#+end_src

#+begin_src latex :noweb yes
\begin{solution}

\begin{tikzpicture}
<<pic.十每.1.base>>
\coordinate (E) at (intersection of D--$(C)+($(D)-(B)$)$ and C--A);

\draw [dashed] (C) -- (E) -- (D);

% 标点
\foreach \i/\angle in {E/0} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}

\[
  \begin{aligned}
  & \mbox{延长} AC \mbox{至} E, \quad CE=MB, \quad \mbox{连结} ED \\
  & \because \angle MDN = 60 \degree, \angle BDC = 120 \degree \\
  & \therefore \angle DCN = \angle ABD = 90 \degree \\
  & \therefore \angle DCE = 90 \degree \\
  & \mbox{在} \triangle MBD \mbox{和} \triangle DCE \mbox{中} \\
  & \begin{cases}
      & DC = DB \\
      & CE = MB \\
      & \angle DCE = \angle MBD
    \end{cases} \\
  & \therefore \triangle MBD \cong \triangle ECD \\
  & \therefore MD = DE \\
  & \mbox{在} \triangle MDN \mbox{和} \triangle EDN \mbox{中} \\
  & \begin{cases}
      & MD = DE \\
      & DN = DM \\
      & \angle MDN = \angle EDN
    \end{cases} \\
  & \therefore \triangle MDN \cong \triangle EDN \\
  & \therefore MN = BM + NC \\
  & \therefore \triangle AMN \mbox{的周长为} 8
  \end{aligned}
\]
\end{solution}
#+end_src

#+RESULTS:
#+begin_export latex
\begin{solution}

\begin{tikzpicture}
\coordinate (B) at (0, 0);
\coordinate (C) at (2.5, 0);
\coordinate (A) at ($(B)!1!60:(C)$);

\coordinate (D) at (intersection of B--$(B)!2!-30:(C)$
                                 and C--{$(C)!2!30:(B)$});

\coordinate (M) at (intersection of D--$(D)!1!45:(A)$
                                 and A--B);

\coordinate (N) at (intersection of D--$(D)!2!-60:(M)$ and C--A);

% 画线
\draw (A) -- (B) -- (C) -- cycle
(B) -- (D) -- (C)
(D) -- (M) -- (N) -- cycle
;

% 标点
\foreach \i/\angle in {A/90,B/-135,C/-45,D/-90,M/135,N/0} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\coordinate (E) at (intersection of D--$(C)+($(D)-(B)$)$ and C--A);

\draw [dashed] (C) -- (E) -- (D);

% 标点
\foreach \i/\angle in {E/0} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}

\[
  \begin{aligned}
  & \mbox{延长} AC \mbox{至} E, \quad CE=MB, \quad \mbox{连结} ED \\
  & \because \angle MDN = 60 \degree, \angle BDC = 120 \degree \\
  & \therefore \angle DCN = \angle ABD = 90 \degree \\
  & \therefore \angle DCE = 90 \angle \\
  \end{aligned}
\]
\end{solution}
#+end_export

*** 问答题 P2-2
如图，已知 $\triangle ABC$ 是等边三角形，点 $D$ 在边 $BC$ 上， $DE \pxx AB$ 交 $AC$ 于 $E$ , 延长 $DE$ 至点 $E$ ,
使 $EF=AE$ ,联结 $AF$ 、 $BE$ 和 $CF$ .

#+begin_src latex
\begin{tikzpicture}
\coordinate (B) at (0, 0);
\coordinate (C) at (2.5, 0);
\coordinate (A) at ($(B)!1!60:(C)$);
\coordinate (D) at ($(B)!.7!(C)$);
% 画线
\draw (A) -- (B) -- (C) -- cycle;

% 标点
\foreach \i/\angle in {A/-180,B/-135,C/-45,D/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}

\end{tikzpicture}
#+end_src

#+latex: \begin{parts}

\part 求证： $\triangle EDC$ 是等边三角形；

\part 找出图中所有的全等三角形，用符号“二”表示，并对其中的一组加以证明；

\part 若 $BE \perp AC$ , 试说明点 $D$ 在 $BC$ 上的位置．

#+latex: \end{parts}

** 十每（第二周）
*** 问答题3
要建造一个面积为 $150$ 平方米的矩形仓库，为了节省原料，仓库的一边靠墙，墙长为 $a$ 米，
另三边用铁栅栏围成，且在与墙平行的一边开一扇 $2$ 米宽的门，已知铁栅栏总长为 $33$ 米。

#+LATEX: \begin{parts}
\part
当 $a=25$ 时，求矩形仓库的长与宽分别为多少？

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
  & \mbox{设垂直于墙为} x \\
  & x(35-2x) = 150 \\
  & -2x^{2} + 35x - 150 = 0 \\
  & (x - 10)(-2x + 15) = 0 \\
  & x_{1} = 10 \quad x_{2} = frac{15}{2} \\
  & \mbox{当} x_{1} = 10 \mbox{时} 35-2x=15 \\
  & \mbox{当} x_{2} = \frac{15}{2} \mbox{时} 35-2x=20 \\
  & \mbox{答： 长为} 10, \mbox{宽为} 15 \quad \mbox{或} \quad \mbox{长为} \frac{15}{2}, \mbox{宽为} 20 \mbox{。}
  \end{aligned}
\]
\end{solution}
#+end_src

\part
题中的墙长 $a$ 对矩形仓库的长与宽有怎样的影响？请具体说明。

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \mbox{当} a \geq 20 \mbox{时} \quad \mbox{两者都行} \\
    & \mbox{当} 15 \leq a \leq 20 \mbox{时} \quad \mbox{长为} 10 \mbox{宽为} 15 \\
    & \mbox{当} a \leq 15 \mbox{时} \quad \mbox{不存在}
  \end{aligned}
\]
\end{solution}
#+end_src

#+LATEX: \end{parts}

*** 问答题 P2-1
如图，某农场利用夹角为135°的两面墙，再用总长为24米的铁丝网围成一个 为42平方米的直角菜园（图中为ABCD),求AB,BC的长为多少米？

#+begin_src latex
\begin{tikzpicture}
\coordinate (D) at (0,0);
\coordinate (C) at (-2,-2);
\coordinate (A) at (4,0);
\coordinate (B) at (4,-2);
\coordinate (E) at (0,-2);

\draw[-] (A) -- (B) -- (C) -- (D) -- cycle;

\foreach \i/\angle in {A/45,B/-45,C/225,D/135,E/-90} {
  \node[dot, label={[dot label]\angle:$\i$}] at (\i) {};
}
\end{tikzpicture}
#+end_src

*** 问答题 P3-情景对话-例10
春秋旅行社为吸引市民组团去天水湾风景区旅游，推出了如下的对话中收费标准.
1. 如果人数超过25人，人均旅游费用为1000元，
2. 如果人数超过25人，每增加1人，人均旅游费用降低20元，但人均旅游费用不得低于700元．
某单位组织员工去天水湾风景区旅游，共支付给春秋旅行社旅游费用27000元．请问该单位这次共有多少员工去天水湾风景区旅游？

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \mbox{设有} x \mbox{人参加} \\
    & \begin{aligned}
      & \textcircled{1} x \leq 25 \\
      & \begin{aligned}
         1000 x &= 27000 \\
              x &= 27 \\
        \end{aligned} \\
      & x=27 \mbox{不符合题意，舍}
      \end{aligned}
    \qquad
    \begin{aligned}
      & \textcircled{2} x > 25 \\
      & \begin{aligned}
          x(1000 - 20(x - 25)) &= 27000 \\
               x(50 - x + 25) &= 1350 \\
                 75x - x^{2} &= 1350 \\
                 x^{2} -75x + 1350 = 0 \\
        \end{aligned} \\
       & x_1 = 30 \qquad x_2 = 45 \\
       & x_2 = 45 \mbox{不符合题意，舍} \\
       & x_1 = 30 \mbox{符合题意}
    \end{aligned} \\
    & \mbox{答：这次共有30人去天水湾风景区旅游}
  \end{aligned}
\]
\end{solution}
#+end_src

*** 问答题 P4-2                                                   :no_answer:
某商品进价为每件 $40$ 元，如果售价为每件 $50$ 元，每个月可卖出 $210$ 件，如果售价超过 $50$ 元，但不超过 $80$ 元，
每件商品的售价每上涨 $1$ 元，每个月少卖 $1$ 件，如果售价超过 $80$ 元后，若再涨价，每件商品的售价每涨 $1$ 元，
每个月少卖 $3$ 件。设该商品的售价为 $x$ 元。

#+LATEX: \begin{parts}
\part
每件商品的利润为 \fillin[ $x-40$ ] 元。
若超过 $50$ 元，但不超过 $80$ 元，每月售 \fillin[ $260-x$ ] 件。
若超过80元，每月售 \fillin[ $420 - 3x$ ] 件。（用 $x$ 的式子填空。）

\part
若超过 $50$ 元但是不超过 $80$ 元，售价为多少时 利润可达到 $7200$ 元

#+begin_src latex
\begin{solution}[1in]
\[
  \begin{aligned}
    & \begin{aligned} 
      (260 - x)(x - 40) &= 7200 \\
      260x - x^{2} +40x &= 17600 \\
      x^{2} - 300x + 17600 &= 0
      \end{aligned} \\
    & x = 220 \mbox{或} x = 80 \\
    & x = 220 \mbox{不符合题意，舍} \\
    & x = 80 \mbox{符合题意} \\
    & \mbox{答：售价为} 80 \mbox{元，利润可达} 7200 \mbox{元}
  \end{aligned}
\]
\end{solution}
#+end_src

\part
若超过 $80$ 元，售价为多少时利润为 $7500$ 元。

#+begin_src latex
\begin{solution}[1in]
\end{solution}
#+end_src

#+LATEX: \end{parts}

* 欣竹
** 待补充
*** 熟练 1.2 
方程 $5x^{2}-4\sqrt{5}x+4=0$ 的根号判别式的值为 \fillin[0] ，该方程 \fillin[有] 实数跟。
*** 熟练 1.3
关于x的一元二次方程 $(m-1)x^{2}+2mx+m+3=2$ 有两个不相等的实数根，那么m的范围 \fillin[ $m < 3/2 \mbox{且} m \ne 1$ ]

*** 熟练  2.1
计算各题
当 $m$ 取何值时，关于 $x$ 的方程 $mx^{2} + 2x -1 = 0$ 有两个实数根:

#+begin_src latex
\begin{solution}[.5in]
  \[
    \begin{aligned}
    & \begin{cases}
      m \neq 0 \\qrt

      \Delta > 0 \\
    \end{cases} \\
    & \begin{aligned}
      & \begin{aligned}
        \Delta &= 6^{2} - 4ac \\
               &= 4 + 4m \\
        \end{aligned} \\
        & 4+4m \geq 0 \\
        & m \geq -1 \\
      \end{aligned} \\
    \end{aligned}
  \]
\end{solution}
#+end_src

*** 拓展 1
求证：不论实数 $m$ 取何值，关于 $x$ 的方程 $(m^{2} + 1)x^{2}+2mx+m^{2}+4=0$ 没有实数根。

#+begin_src latex
\begin{solution}[1in]
  \[
    \begin{aligned}
      & \Delta = -4m^{4} -16m^{2} - 16 \\
      & \because m^{4} \geq 0 \qquad m^{2} \geq 0 \\
      & \therefore \Delta \le 0 \\
      & \therefore \mbox{无实根} \\
    \end{aligned}
  \]
\end{solution}
#+end_src

*** 探究 1                                                        :no_answer:
$k$ 为何值时，方程 $(k-1)x^{2}-(2k+3)x+(k+3)=0$ 有实数根？

#+begin_src latex
\begin{solution}[1in]
\end{solution}
#+end_src

*** 探究 2                                                        :no_answer:
若 $m$ 为非负整数，且一元二次方程 $(1-m^{2})x^{2}+2(1-m)x-1=0$

#+begin_src latex
\begin{solution}[1in]
\end{solution}
#+end_src
