#+TITLE: 初中时政资料
:PROPERTIES:
#+STARTUP: content
#+STARTUP: noptag
#+STARTUP: hideblocks
#+OPTIONS: author:nil date:nil title:nil toc:nil
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \newgeometry{left=1cm, right=1cm, top=1cm, bottom=1cm}
:END:

* 2020年9月
** 国内部分
1. 2020年9月1日 *广西平南三桥桥面格子顺利合龙* 。 至此，大桥15000吨主体钢结构全部安装完成，主桥南北实现贯通， *预计年底建成通车 ，建成通车后将为世最大跨径拱桥* 。

2. 2020年9月1日电 *浙江大学联合之江实验室9月1日在杭州发布一款包含1.2亿脉冲神经元、近千亿神经突触的类脑计算机* 。该计算机使用了792颗由浙江大学研制的达尔文2代类脑计算芯片集成在3台1.6米高的标准服务器机箱中，形成一台机架式类脑计算机。 *神经元数量规模相当于小鼠大脑* 。

3. 2020年9月3日，国家主席习近平同俄罗斯总统普京互致贺电， *庆祝世界反法西斯战争胜利75周年* 。习近平强调，中俄同为联合国安理会常任理事国,对世界和平发展事业负有重要责任。我愿继续同你共同努力， *以纪念世界反法西斯战争胜利75周年为契机 引领中俄两国深化全面战略协作，同国际社会一道，坚定捍卫二战胜利成果和国际公平正义,积极维护和践行多边主义，推动构建人类命运共同体，让子孙后代享有持久和平、普遍安全、共同繁荣的世界。*

4. 2020年9月3日电，商务部办公厅近日发布了《关于进一步加强商务领域塑料污染治理工作的通知》，公布了禁塑限塑阶段性任务，要求 *到2022年底全国范围内星级宾馆、酒店等场所不再主动提供一次性塑料用品* 。到2025年底,实施范围扩大至所有宾馆、酒店、民宿。

5. 2020年9月4日，中宣部、教育部公布2020年全国教书育人楷模名单。12位全国教书育人楷模涵盖了高教、职教、基教、幼教、特教等各级各类教育, 同时兼顾了地域、民族、性别、年龄等因素。他们是: 清华大学附属小学校长、教师 *窦桂梅* ，天津中医药大学校长、教授 *张伯礼* ，东北师范大学教授 *高夯* ，安徽省宿州市埇桥区汴河中心小学教师 *孙浩* ，山东省潍坊商业学校教师 *魏亚丽* ，华中科技大学教授 *胡豫* ，广州医科大学教授 *钟南山* ，海南大学教授 *张云阁* ，四川省泸州市特殊教育学校教师 *肖敏* ，贵州省毕节市赫章县城关镇中心幼儿园教师 *何梅* ，云南省丽江市华坪女子高中教师 *张桂梅* 和陕西省咸阳市旬邑县马栏齐心九年制寄宿学校教师 *丁海燕* 。

6. 2020年9月4日，中国科学院高能物理研究所表示， *慧眼(HXMT)卫星团队* 通过对X射线吸积脉冲星GRO J008 - 57的详细观测，采用直接测量的方法得到该脉冲星表面磁场强度为约10亿特斯拉,这是迄今为止， *人类直接且非常可靠地测量到的宇宙中的最强磁场* 。

7. 2020年9月5日，中国工业和信息化部部长肖亚庆在北京表示，当前中国5G用户已超过6000万, *今年将推动5G大规模商用* 。

8. 2020年9月6日电， *我国在酒泉卫星发射中心成功发射的可重复使用航天器* ，在轨飞行2天后，于9月6日成功返回预定着陆场。这次试验的圆满成功,标志着我国可重复使用航天器技术研究取得重要突破，后续可为和平利用太空提供更加便捷、廉价的往返方式。

9. 2020年9月6日，2020年未来科学大奖今天上午在北京揭晓，哈尔滨医科大学第一附属医院教授 *张亭栋* 和上海交通大学医学院附属瑞金医院教授 *王振义获生命科学奖* ，中国科学院金属研究所研究员 *卢柯获物质科学奖* ，山东大学教授 *彭实戈获数学与计算机科学奖* 。

10. 2020年9月7日，住房和城乡建设部就《住房租赁条例(征求意见稿)》向社会公开征求意见。其中征求意见稿明确，住房租赁企业不得以隐瞒、欺骗、强迫等方式要求承租人使用住房租金贷款，不得以租金优惠等名义诱导承租人使用住房租金贷款,不得在住房租赁合同中包含租金贷款相关内容。国家 *鼓励住房租赁企业与承租人签订租赁期限为3年以上的住房租赁合同* 。

11. 2020年9月8日，国家航天局表示，为褒扬中国探月工程总设计师吴伟仁院士在月球与深空探测领域的突出贡献， *国际天文学联合会(IAU)小行星命名委员会批准将编号为281880号的小行星正式命名为“吴伟仁星”* 。

12. 2020年9月8日电，近日CRH380AJ型高速综合检测车首次试跑连淮扬镇铁路扬州段，这是 *目前世界上运行速度最高的检测列车，极限时速可以达400公里* 。因该组动车为黄色，被比喻为“黄医生”。

13. 2020年9月9日电,经党中央、中央军委批准，《中国共产党军队党的建设条例》日前颁布施行。 *《条例》以党章为根本遵循* ，落实新时代党的建设总要求，坚持党对军队绝对领导，坚持全面从严治党，坚持聚焦备战打仗。 *《条例》是全面规范军队党的建设的基础主干党内法规，是推进军事政策制度改革的重要成果，标志着我军党的建设科学化、规范化、制度化水平迈.上新台阶* 。

14. 2020年9月10日，在第三十六个教师节到来之际，中央宣传部、教育部向全社会公开发布 *2020年“最美教师”先进事迹。其中张文宏、王易、戚发轫、高文铭、张杰、王秀秀、刘秀祥、蒋春凌、王菲华雨辰、马文燕等个人和凉山支教帮扶团队入选* 。

16. 2020年9月12日电，日前，在中国一重集团大连核电石化公司，一只70多米长的“银瓶”被组装完成后运出厂房 -- *全球首台3000吨超级浆态床锻焊加氢反应器如期交付* 。

17. 2020年9月13日电，财政部表示：为落实党中央、国务院关于加强乡村教师队伍建设决策部署, *“十三五”时期中央财政共安排700亿元，支持和引导地方加强乡村教师队伍建设，提升教育教学质量* 。其中，安排17亿元，通过实施“三区”人才支持计划教师专项计划和“银龄讲学"计划，鼓励优秀教师到贫困地区、民族地区、革命老区、边疆地区支教。

18. 2020年9月14日，国家主席习近平在北京同欧盟轮值主席国德国总理默克尔、欧洲理事会主席米歇尔、欧盟委员会主席冯德莱恩共同举行会晤，会晤以视频方式举行，中欧双方宣布签署 *《中欧地理标志协定》* 确认加快中欧投资协定谈判，实现年内完成谈判的目标。会上习近平强调，中欧要做到 *“4个坚 持”，坚持和平共处、坚持开放合作、坚持多边主义、坚持对话协商* 。

19. 2020年9月15日9时23分,我国在黄海海域用长征十一号海射运载火箭， *采取“一箭九星”方式 将“吉林一号”高分03 -- 1组卫星送入预定轨道，发射获得圆满成功* 。这是长十一火箭执行的第二次海上发射任务，也是我国第一次海上商业化应用发射，标志着我国已经具备稳定高效的海上发射能力。

20. 2020年9月15日，新建福(州)厦(门)高铁泉州湾跨海大桥主塔封顶。全长20.29公里， *泉州湾跨海大桥也是世界首座行车速度超过350公里/小时的跨海大跨斜拉桥* 。

21. 2020年9月16日， *习近平总书记赴湖南考察调研* 。他来到郴州市汝城县文明瑶族乡沙洲瑶族村 “半条被子的温暖”专题陈列馆、村服务中心和卫生室、沙洲现代农旅示范基地、文明瑶族乡第一片小学，以及村民家中， *了解当地开展红色教育、发展扶贫产业、巩固脱贫成果等情况* 。

22. 2020年9月16日，是 *第二十六个国际保护臭氧层日* ，也是《保护臭氧层维也纳公约》缔结35周年，生态环境部于16日召开2020年中国国际保护臭氧层日纪念大会。会上表示， *我国累计淘汰消耗臭氧层物质超过28万吨* ，为臭氧层保护和温室气体减排做出积极贡献。

23. 2020年9月17日，国务院总理李克强主持召开国务院常务会议，指出，要 *坚持“两个毫不动摇”，支持国企和民企改革发展* 。要持续推进国企提质增效，提高核心竞争力，增强发展后劲，更好发挥在国民经济中的支撑作用；进一步为民营企业发展创造公平竞争环境，带动扩大就业。

24. 2020年9月19日， *中国延安精神研究会第六次会员大会在京召开* ，国家主席习近平发来贺信， *向大会的召开和研究会成立30周年表示热烈祝贺* 。习近平在贺信中指出，延安是中国革命的圣地，老一辈革命家和老一代共产党人在延安时期培育形成的延安精神是我们党的宝贵精神财富。希望同志们在新的历史条件下，坚持正确政治方向，服务党和国家工作大局，深入研究、大力宣传、认真践行延安精神，努力为全面建成小康社会、乘势而上开启全面建设社会主义现代化国家新征程提供强大精神动力。

25. 2020年9月19日，为进一步推进北京市长城国家文化公园和长城文化带建设，经国家文物局同意， *北京市在怀柔区雁栖镇西栅子村建立长城保护修复实践基地并举行挂牌仪式* 。据悉，这是 *我国长城沿线首个挂牌的长城保护修复实践基地* 。

26. 2020年9月19日，定远舰遗址水下考古队在广州打捞局的协助下，成功将一块定远舰铁甲起吊出水， *定远舰铁甲是目前国内出水唯一一块北洋海军铁甲舰装备的护防装甲* 。

27. 2020年9月20日，*第十二届海峡论坛在厦门举行* ，全国政协主席汪洋在大会上发表视频致辞，强调我们 *坚持在“九二共识”基础上推进两岸关系和平发展，着眼点和落脚点就是增进同胞的亲情和福扯，让两岸同胞过上更加美好的生活* 。

28. 2020年9月20日，历时30个月的建设，我 *国首个自营深水油田群 -- 流花16-2油田群顺利投产。这也是目前我国在南海开发产量最大的新油田群* ，高峰年产量可达420万立方米，能够满足400多万辆家用汽车一年的汽油消耗。

29. 2020年9月22日，北京大兴国际机场迎来第1000万名旅客，标志着 *北京大兴国际机场自投运以来旅客吞吐量首次突破千万人次大关* 。

30. 2020年9月22日电，自然资源部办公厅、财政部办公厅、生态环境部办公厅日前联合印发《山水林田湖草生态保护修复工程指南（试行）》。明确实施 *“山水工程”要遵循5方面保护修复原则，包括生态优先、绿色发展，自然恢复为主、人工修复为辅，统筹规划、综合治理，问题导向、科学修复，经济合理、效益综合* 。

31. 2020年9月22日， *成都多灾种预警工程技术研究中心正式揭牌，标志着全国首个多灾种预警工程技术研究中心正式成立* 。

32. 2020年9月23日电，国务院办公厅日前印发《关于加快医学教育创新发展的指导意见》，提出四个方面举措。 *一是全面优化医学人才培养结构；二是全力提升院校医学人才培养质量；三是深化住院医师培训和继续医学教育改革；四是完善保障措施* 。

33. 2020年9月24日电，近日，自然资源部海底科学重点实验室科研团队自主研发的 *“海豚”移动式海洋地震仪* 圆满完成海试工作。这是 *国内首台移动式海洋地震仪* ，最大下潜深度1050米。

34. 2020年9月25日， *大陆首家两岸合资证券公司 -- 金圆统一证券有限公司在厦门揭牌开业* 。

35. 2020年9月26日，国家 *“东数西算”产业联盟在甘肃省兰州市成立* 。这个产业联盟将搭建东西部算力供需对接平台，优化我国东中西部算力资源协同发展格局，有助于形成自由流通、按需配置、有效共享的数据要素市场。

36. 2020年9月27日电，近日，河北省十三届人大常委会第十九次会议全票通过 *《河北省人民代表大会常务委员会关于厉行节约、反对餐饮浪费的规定》* ，将于2020年11月1日起实施。这是 *全国首部专门聚焦治理餐饮浪费的省级地方性法规* ，被认为是给破解餐饮浪费焦点难点问题提供了法治方案，受到社会的关注和期待。

37. 2020年9月27日，日前，最高人民法院召开新闻发布会，发布 *《长江流域生态环境司法保护状况》白皮书，这是首个专项生态环境司法保护白皮书* 。

38. 2020年9月28日，国家电力投资集团有限公司在上海发布中国 *三代核电自主化成果“国和一号”* ，“国和一号”是国际公认的、代表世界三代核电先进水平的技术型号，“国和一号”是完全自主设计的中国核电技术品牌， *标志着中国完全具备先进核电自主化能力* 。

39. 2020年9月28日，*国产高原无人直升机AR-500C在四川稻城亚丁机场创造了海拔4411米的国产无人直升机起降高度新纪录* ，基本具备全疆域飞行能力。

40. 2020年9月29日电， *《浙江省大运河世界文化遗产保护条例》* 近日审议通过，将于2021年1月1日起正式施行。《条例》共36条，是 *国内第一部关于大运河世界文化遗产保护的省级地方性立法* 。

** 国际部分
1. 2020年9月1日电， *黎巴嫩总统米歇尔・奥恩8月31日任命穆斯塔法・阿迪卜为新总理* ，并授权其组阁。

2. 2020年9月1日，纪念联合国成立75周年国际研讨会在北京举行。本次研讨会以 *“加强多边主义，共创美好未来”* 为主题。

3. 2020年9月2日， *日本内阁官房长官菅义伟宣布，他决定参加自民党总裁选举* 。菅义伟将同日本自民党政务调查会长岸田文雄和前自民党干事长石破茂竞选总裁职位，获胜者将接替此前宣布辞职的现任总裁、日本首相安倍晋三。

4. 2020年9月5日电，美国华盛顿大学健康指标与评估研究所（IHME发布报告，指出美国新冠病亡率高于多个国家，从死亡病例数据来看， *新冠肺炎已超越癌症，成为美国第二大死因，排名仅次于心脏病* 。

5. 2020年9月7日，据《印度斯坦时报》报道， 印度成功在奥里萨邦巴拉索尔的阿卜杜尔・卡拉姆测试场进行了 *“高超声速试验验证飞行器”(HSTVD)飞行测试* ，这标志着 *印度成为继美国、俄罗斯和中国之后第四个开发并成功测试高超声速技术的国家* 。

6. 2020年9月10日电，近日，世界自然基金会的一份报告显示， *全球野生动物数量在不到50年的时间内锐减了三分之二以上* ，并且这种“灾难性的下降趋势”没有减缓迹象。

7. 2020年9月11日，英国政府宣布，已与日本达成贸易协议。这是 *英国自今年1月31日“脱欧”后达成的首份重大贸易协议* 。

8. 2020年9月14日，日本自民党举行总裁选举， *内阁官房长官营义伟以绝对优势胜出，“接班”因病辞职的安倍* 。如无意外，两天之后的9月16日，他将成为日本第99任首相。

9. 2020年9月15日电，非洲疾病预防控制中心与世界卫生组织近日联合启动了一个实验室网络，以加强非洲新冠病毒基因组测序工作。 *该网络由12个实验室组成，将为实验室所在国家及周边地区提供基因测序、数据分析及其他技术支持服务* 。

10. 2020年9月16日，经合组织发布了《经济展望中期报告》，将全球2020年GDP变动预期从下滑6%上调至萎缩4.5%, 2021年经济增长预期同步上调至5%。此外，报告指出，按照目前的经济和疫情态势， *中国将是2020年二十国集团中唯一实现正增长的国家* 。

11. 2020年9月17日电，德国联邦政府和各州政府日前召开视频会议，决定 *同意各职业体育联赛主办方在新赛季允许球迷进入赛场观赛，人数上限是赛场容量的20%* 。

12. 2020年9月21日，日本总务省发布数据，称该国 *65岁以上的老年人口数量达3617万人* ，在总人口中的占比为28.7%， *为全球最高，均为有记录以来的最高值* 。

13. 2020年9月21日，美国司法部宣布，美国 *纽约、波特兰和西雅图* 这三大城市，已被正式列为 *“无政府主义管辖区”* 。

14. 2020年9月22日，联合国秘书长古特雷斯指出，当今世界面临五大挑战： *地缘紧张局势、气候危机、全球互不信任、数字世界黑暗面及新冠疫情全球大流行* 。

15. 2020年9月23日电， *智利* 天文学家领衔的一个国际团队在新一期英国《自然・天文学》杂志上报告说，在距地球约260光年的一个星系中发现了 *第一颗“超热海王星”* ，这是此前仅在理论上存在的一类特殊行星。

16. 2020年9月24日，联合国秘书长古特雷斯发表讲话，呼吁国际社会 *以创新方式思考全球治理和多边主义* ，以适应21世纪的需要。

17. 2020年9月25日，富时罗素公司宣布 *中国国债将被纳入富时世界国债指数(WGBI)* 。

18. 2020年9月26日电，因疫情影响延期的 *东京奥运会火炬接力，将定于2021年3月25日举行* 。照此前计划，火炬接力将于121天内在全日本范围内进行。

19. 2020年9月27日， *阿塞拜疆总统阿利耶夫签署法令，宣布国家进入战争状态* ，并在全国范围实行戒严令。

20. 2020年9月29日晚间， *美国总统特朗普和民主党总统提名人拜登首次辩论会在俄亥俄州的克利夫兰登场* 。

* 2020年10月
** 国内部分
1. 2020年10月1日出版的第19期《求是》杂志将重新发表国家主席习近平在出席庆祝中华人民共和国成立70周年系列活动时的3篇重要讲话：2019年10月1日《在庆祝中华人民共和国成立70周年大会上的讲话》、2019年9月30日《在庆祝中华人民共和国成立70周年招待会上的讲话》、2019年9月29日《在国家勋章和国家荣誉称号颁授仪式上的讲话》。讲话指出， *一切伟大成就都是接续奋斗的结果，一切伟大事业都需要在继往开来中推进。新时代必将是大有可为的时代* 。

2. 2020年10月2日，国家卫健委在官方网站发布《中华人民共和国传染病防治法》。拟重构传染病疫情信息公布制度， *传染病暴发、流行时，由县级以上地方人民政府卫生健康主管部门公布本行政区域内疫情信息；传染病出现跨省暴发、流行时，由国务院卫生健康主管部门负责公布* 。

3. 2020年10月2日电，近日，国务院学位委员会、教育部印发了《专业学位研究生教育发展方案 (2020-2025)》，提出 *到2025年* ，增设一批硕士 、博士专业学位类别， *将硕士专业学位研究生招生规模扩大到硕士研究生招生总规模的三分之二左右* ，并大幅增加博士专业学位研究生招生数量。

4. 2020年10月3日电，国家医疗保障局和财政部日前联合发布《关于推进门诊费用跨省直接结算试点工作的通知》，决定在 *北京、天津、河北、上海、江苏、浙江、安徽、重庆、四川、贵州、云南、西藏12个省（区、市）进行门诊费用跨省直接结算试点* 。

5. 2020年10月4日，国家主席习近平同 *孟加拉国* 总统哈米德互致贺电，热烈庆祝 *两国建交45周年* 。 习近平在贺电指出，建交45年来，两国始终相互尊重、平等相待，增强政治互信，深化互利合作，为两国人民带来实实在在福祉。

6. 2020年10月4日电，近日 *我国完成首次大型无人机应急通信实战演练* ，以“翼龙”-2为平台搭建区域空间通信网，在无信号区域提供有效通信覆盖。

7. 2020年10月5日， *三峡集团白鹤滩水电站* 左岸地下厂房最后一仓混凝土浇筑完成，标志着 *世界最大的地下厂房全线封顶* 。

8. 2020年10月6日电，中国天文学家主导的国际科研团队最新通过监测恒星“心跳”形成的“心电图”发现， *绝大多数富锂巨星其实都是红团簇星* ，而不是传统上所认为的红巨星。这一发现挑战了传统的恒星演化理论，为最终解开锂元素起源之谜迈出关键一步。

9. 2020年10月7日电，近日，教育部公布《关于加强博士生导师岗位管理的若干意见》，提出 *避免简单化地唯论文、唯科研经费确定博士生导师选聘条件* 。提出要建立国家典型示范、省级重点保障、培养单位全覆盖的三级培训体系。要求博士生导师的首要任务是人才培养，承担着对博士生进行思想政治教育、学术规范训练、创新能力培养等职责，要严格遵守研究生导师指导行为准则。

10. 2020年10月8日电，国庆假期， *福建平潭海峡公铁两用大桥试通车* 。该桥是 *我国首座跨海公铁两用桥* ，上层为设计时速100公里的6车道高速公路，下层为设计时速200公里的双线1级铁路。

11. 2020年10月8日电，美国物理学会近日公布授予 *中国科学技术大学陆朝阳教授2021年度“兰道尔一本内特量子计算奖”* ，表彰他“在光学量子信息科学，特别是在固态量子光源、量子隐形传态和光量子计算方面的重要贡献”。

12. 2020年10月9日， *西藏昌都各族各界隆重庆祝解放70周年* 。藏东古城昌都的解放，奠定了和平解放西藏的基础，开启了西藏历史的新纪元。

13. 2020年10月10日电，日前，上海市、江苏省、浙江省共同发布了《长三角生态绿色一体化发展示范区政府核准的投资项目目录（2020年本）》。 据悉，这是 *我国第一个跨省域的政府核准的投资项目目录* 。

14. 2020年10月11日电，生态环境部卫星环境应用中心 *长江生态监控基地* 近日在 *江苏泰兴市* 揭牌，这是长江流域建成的 *首个集检测、评估、预警于一体并开展应用的大数据平台* 。

15. 2020年10月12日电，北京时间10月12日0时57分，中国在西昌卫星发射中心用长征三号乙运载火箭，成功将 *高分十三号卫星* 发射升空，卫星顺利进入预定轨道。高分十三号卫星是高轨光学遥感卫星，主要用于国土普查、农作物估产、环境治理、气象预警预报和综合防灾减灾等领域，可为国民经济发展提供信息服务。

16. 2020年10月12日， *中国广电网络* 股份有限公司在京召开成立大会， *将成为第四大电信运营商* 。这是推进全国有线电视网络整合和广电5G建设一体化发展迈出的重要一步。

17. 2020年10月13日， *丽江至香格里拉铁路金沙江特大桥实现合龙* ，为丽香铁路如期通车打下了坚实基础。该桥是 *世界上首座大跨度钢桁梁铁路悬索桥* 。

18. 2020年10月13日，刑法修正案（十一）草案二审稿提请全国人大常委会会议审议，拟在特定情形下，经特别程序， *对法定最低刑事责任年龄作个别下调* 。草案规定， *已满12周岁不满14周岁的人* ，犯故意杀人、故意伤害罪，致人死亡，情节恶劣的，经最高人民检察院核准，应当负刑事责任。

19. 2020年10月14日，最高人民法院、最高人民检察院、公安部联合发布《关于依法办理“碰瓷” 违法犯罪案件的指导意见》， *首次明确了对“碰瓷”行为的法律界定* ，即行为人通过故意制造或者编造其被害假象，采取诈骗、敲诈勒索等方式非法索取财物的行为。

20. 2020年10月14日，袁隆平“海水稻”团队和江苏省农业技术推广总站合作试验种植的 *“超优千号”耐盐水稻* 的平均亩产量达到802.9公斤，这个产量创下盐碱地水稻高产新纪录。

21. 2020年10月15日，国家主席习近平同 *赤道几内亚* 总统奥比昂互致贺电，庆祝两国建交50周年。

22. 2020年10月16日， *凤凰黄河大桥* 主桥钢箱梁顺利完成合龙。该桥主桥全长1332米，整幅全宽61.7米，是 *黄河上最宽的大桥，其桥梁跨径以及梁宽均居同类型桥梁世界之最* 。

23. 2020年10月16日， *宁夏* 大气污染源排放清单编制项目日前整体通过专家验收，成为 *中国首个实现源清单全覆盖的省区* 。

24. 2020年10月17日，十三届全国人大常委会第二十二次会议表决通过关于 *修改国旗法、国徽法的决定，决定将于2021年1月1日起施行* 。根据新法，在公共场合故意以 *焚烧、毁损、涂划、站污、践踏等方式侮辱国旗、国徽* 的，依法追究刑事责任；情节较轻的，由公安机关处以十五日以下拘留。

25. 2020年10月18日电， *河北省* 十三届人大常委会第十九次会议日前审议通过关于厉行节约、反对餐饮浪费的规定，将于今年11月1日起实施。这是 *全国首部专门聚焦治理餐饮浪费的省级地方性法规* ，为破解餐饮浪费焦点难点问题提供法治方案。

26. 2020年10月18日，国新办举行新闻发布会，介绍扎实推动深圳综合改革试点落地见效有关情况，会上 *《深圳建设中国特色社会主义先行示范区综合改革试点首批授权事项清单》* 正式发布，此次综合改革试点，首次采取 *“实施方案＋授权清单”* 滚动推进的全新方式授权改革。

27. 2020年10月19日，在第六届中国（国际） 商业航天高峰论坛上，中国航天科工集团表示，我国正在建设的首个 *卫星物联网―“行云工程”* 进展顺利，预计 *将于2023年前后建设完成由百余颗卫星组成的“物联网星座”* 。目前第一阶段建设任务已全面完成。

28. 2020年10月19日，我国自主设计建造的多用途滚装船 *“渤海恒达”轮* 在中集来福士山东龙口厂区下水，这是 *目前亚洲最大的多用途滚装船* 。

29. 2020年10月20日电，70年来， *淮河治理* 总投入近1万亿元，直接经济效益接近5万亿元，这是 *新中国第一条全面系统治理的大河* 。

30. 2020年10月21日电， *全国第二处“林业英雄林”日前在山东省淄博市原山林场落成* 。

31. 2020年10月22日，公安部在京召开新闻发布会，会上指出，放宽小型汽车驾驶证申请年龄，取消申请小型汽车、小型自动挡汽车、轻便摩托车驾驶证 *70周岁的年龄上限调整为不作限制* 。

32. 2020年10月23日电，民政部2020年第四季度例行新闻发布会上表示：“十四五”期间， *我国老年人口将突破3亿，将从轻度老龄化迈入中度老龄化* 。

33. 2020年10月24日，在纪念中国人民志愿军抗美援朝出国作战70周年之际，中央宣传部以云发布的方式，向全社会宣传发布 *中国人民志愿军老战士孙景坤、徐振明的先进事迹，授予他们“时代楷模”称号* 。

34. 2020年10月25日电，近日，工信部表示，我国已 *连续10年保持世界第一制造大国地位* ，而且 *我国是全世界唯一拥有全部工业类别的国家* 。

35. 2020年10月26日至29日，党的十九届五中全会在京召开。会议将审议中共中央关于制定 *国民经济和社会发展第十四个五年规划和二0三五年远景目标的建议* ，为未来5年乃至15年中国发展璧画蓝图。

36. 2020年10月26日，为适应涉外海事审判需要，破解外国法查明难题， *“上海海事法院外国法查明平台”在沪上线* 。据上海海事法院方面表示，这是 *中国海事审判领域首个外国法查明平台* 。

37. 2020年10月27日，全国人大常委会委员长栗战书在北京人民大会堂出席第六届金砖国家议会论坛视频会议并发表讲话。就金砖国家 *立法机构加强合作* 提出四点建议， *一是加强公共卫生领域合作，依法助力疫情防控；二是坚持开放创新发展，为世界经济复苏提供法治支撑；三是坚定维护国际法权威，推动建设更加公正合理的国际秩序；四是在金砖机制下深化立法机构合作* 。

38. 2020年10月28日电，教育部近日印发了《大中小学国家安全教育指导纲要》，提出 *“将国家安全教育纳入国民教育体系”* 的要求，明确了国家安全教育主要内容，包括政治、国土、军事、经济、文化、社会、科技、网络、生态、资源、核、海外利益等12个领域安全，提出实施国家安全教育的保障要求， *确保“有人管”“有人教”“有载体”* 。

39. 2020年10月29日，中共十九届五中全会在京举行，全会提出了 *到二0三五年基本实现社会主义现代化远景目标* 就是： *基本实现新型工业化、信息化、城镇化、农业现代化，建成现代化经济体系；基本实现国家治理体系和治理能力现代化* ，人民平等参与、平等发展权利得到充分保障，基本建成法治国家、法治政府、法治社会等；全会提出了 *“十四五”时期经济社会发展主要目标* 就是： *经济发展取得新成效，在质量效益明显提升的基础上实现经济持续健康发展* ，增长潜力充分发挥，国内市场更加强大，经济结构更加优化，创新能力显著提升，产业基础高级化、产业链现代化水平明显提高，农业基础更加稳固，城乡区域发展协调性明显增强，现代化经济体系建设取得重大进展等；会议提出， *坚持创新在我国现代化建设全局中的核心地位，把科技自立自强作为国家发展的战略支撑* ；坚持把发展经济着力点放在实体经济上，坚定不移建设制造强国、质量强国、网络强国、数字中国。

40. 2020年10月29日电，近日，国家发改委等14部门印发《近期扩内需促消费的工作方案》。提到，推动线下服务消费加速“触网”，充分释放线上经济潜力。要 *完善“互联网＋”医保支付政策* 。在保证医疗安全和质量前提下， *将慢性病互联网复诊费用纳入医保支付范围* 。

** 国际部分
1. 2020年10月2日下午，欧盟特别峰会结束了两天的既定议程，峰会第二日的关注点由国际议题转为欧盟单一市场运作及数字转型问题，同时与会领导人还就加强协同抗疫达成共识。欧洲理事会特别强调，要 *确保在欧盟境内快速部署5G网络，各成员国须在今年年底之前向欧委会提交5G网络普及方案* 。

2. 2020年10月4日电， *美国海军陆战队近日在关岛设立新基地* ，这是其 *自1952年以来设立的首座新基地* ，预计明年春季启用，届时将承接从日本冲绳转出的约5000名陆战队员。

3. 2020年10月5日，瑞典卡罗琳医学院宣布，将 *2020年诺贝尔生理学或医学奖* 授予 *美国科学家哈维・阿尔特、查尔斯・赖斯* 以及 *英国科学家迈克尔・霍顿* ，以表彰他们在发现 *丙型肝炎病毒* 方面所做出的贡献。

4. 2020年10月6日18时许， *2020年诺贝尔物理学奖* 正式揭晓，一半由 *英国科学家罗杰・彭罗斯* 获得，另一半由 *德国科学家莱因哈德・根泽尔、美国科学家安德里亚・格兹* 共同获得。其中，美国科学家安德里亚・格兹是第四位女性诺贝尔物理学奖得主。

5. 2020年10月7日，瑞典皇家科学院宣布，将 *2020年诺贝尔化学奖* 授予 *法国女科学家埃玛纽埃勒・沙尔庞捷* 和 *美国女科学家珍妮弗・道德纳* ，以表彰她们在 *基因组编辑方法研究领域* 作出的贡献。

6. 2020年10月9日， *巴基斯坦拉合尔轨道交通橙线* 项目顺利完成竣工交付，标志着巴基斯坦 *首条城市轨道交通项目即将投入商业运营* 。该项目是中巴经济走廊框架下首个正式启动的大型城市轨道交通项目。

7. 2020年10月10日，中共中央总书记习近平就 *朝鲜劳动党成立75周年* 向朝鲜劳动党委员长金正恩致贺电。

8. 2020年10月12日电， *2020年诺贝尔经济科学奖* 授予 *保罗・米尔格罗姆* 和 *罗伯特・B威尔逊* ，以表彰他们在“用与改进拍卖理论和新拍卖形式”方面作出的贡献。

9. 2020年10月13日，中国在第75届联合国大会上再次成功当选 *联合国人权理事会成员* ，任期为2021年至2023年。

10. 2020年10月14日，美国食品药品管理局宣布批准了 *全球首个埃博拉病毒治疗方法：“银马泽伯”* 。“银马泽伯”是三种单克隆抗体混合物药物，由美国再生元制药公司生产，在遏制埃博拉死亡率、提高生存率方面实现了突破。

11. 2020年10月16日，由中央党校与联合国经济和社会事务部联合举办的 *首届发展中国家国家治理高端智库论坛在京召开* 。论坛以 *“反贫困的中国经验 -- 加强公共机构在消除贫困和实现可持续发展方面的作用”* 为主题，采用线下论坛和线上会议结合方式进行。

12. 2020年10月18日， *巴林和以色列* 两国官员签署建立双边外交关系的公报，标志着 *两国正式建立外交关系* 。

13. 2020年10月20日电， *美国* 航天局近日宣布， *将与芬兰诺基亚公司在月球上合作开发第一个4G通信网络* 。

14. 2020年10月21日电， *高盛集团不久前将土耳其2020年经济增速由此前预测的萎缩5%调高至萎缩3.5%* 。土耳其财政部长阿尔巴伊拉克近日表示，土耳其经济年内有望触底反弹，迎来V形复苏。

15. 2020年10月23日，日本外务大臣茂木敏充和英国国际贸易大臣伊丽莎白・特拉斯当天在日本首都东京签署《英日全面经济伙伴关系协定》，这是 *英国脱离欧洲联盟后与主要经济体达成的第一份贸易协定* 。

16. 2020年10月25日， *日本* 预计2020年新生儿人数将为大约84.5万人，低于2019年的大约86.5万人， *将连续第五年创新低* 。

17. 2020年10月26日电，欧盟委员会近日公布了旨在提高存量建筑能源效率的建筑翻新计划。根据计划，未来10年欧盟将资助改造3500万栋建筑，将翻新率提高至少一倍，有望创造16万个绿色建筑岗位。

18. 2020年10月27日电，欧盟统计局日前发布数据显示，今年前7个月，欧盟27个成员国与中国进出口总额为3287亿欧元，同比增长约2.6%。 *中国首次成为欧盟第一大贸易伙伴* 。

19. 2020年10月28日电，亚太经合组织粮食安全政策对话部长级视频会举行。与会代表一致同意加强合作，推动 *构建开放和可预见的贸易体系* ，以 *维护创新、可靠、有韧性和可持续的全球粮食体系* 。

20. 2020年10月29日电，韩国银行报告的最新数据显示， *韩国第三季度经济环比增长1.9%* ，特别是出口强势反弹，较二季度增长15.6%。这是 *疫情发生以来韩国经济首次实现环比增长* 。
