#+TITLE: 八年级上英语错题
:PROPERTIES:
#+STARTUP: overview
#+STARTUP: noptag
#+STARTUP: hideblocks
#+OPTIONS: author:nil date:nil
#+TAGS: no_answer(a) \n no_pic(p)
#+LATEX_CLASS: exam
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \newcommand\epart{\part}
#+LATEX_CLASS_OPTIONS: [answers]
:END:

* 重要考试
** 阶段一
*** Choose the best answer 5
I usually spend half of my spare time reading and  \fillin doing my homework.

\begin{oneparchoices}
\correctchoice the other
\choice the others
\choice others
\choice the rest
\end{oneparchoices}

*** Choose the best answer 8
You have been to Beijing. How long \fillin you \fillin there?

\begin{oneparchoices}
\correctchoice will...stay
\choice did...stay
\choice have...stayed
\choice do...stay
\end{oneparchoices}

*** Choose the best answer 9
He promised that he \fillin us how to make a model plane the next week.

\begin{oneparchoices}
\choice will teach
\correctchoice would teach
\choice has taught
\choice had taught
\end{oneparchoices}

*** Choose the best answer 10                                     :no_answer:
His experience of doing business \fillin a hot topic to discuss.

\begin{oneparchoices}
\choice raised
\choice rose
\choice was raised
\choice was risen
\end{oneparchoices}

*** Choose the best answer 11
-- My parents never stop going on about(唠叨)how I should study hard. \\
-- \fillin[].

\begin{oneparchoices}
\choice So my parents do.
\choice Nor my parents.
\choice So do my parents.
\correctchoice Neither do my parents.
\end{oneparchoices}

*** Choose the best answer 12                                     :no_answer:
-- The T-shirt is too small for me. Would you mind giving me a large one?
-- \fillin[]

\begin{oneparchoices}
\choice Yes,please.
\choice I'm busy now.
\choice Not at all.
\choice You're welcome
\end{oneparchoices}

*** Rewrite the sentences as required 3
After a quick breakfast, Mary left in a hurry.(保持句意不变) \\
After a quick breakfast, Mary \fillin[hurried] \fillin[off] .

* 期中复习
** 期中复习卷一
*** Choose the best answer 5
Don’t \fillin[], everyone. Follow me and we’ll get out of from the cave.

\begin{oneparchoices}
\choice fright
\correctchoice panic
\choice afraid
\choice worried
\end{oneparchoices}

*** Choose the best answer 16
\fillin[] Li Hong \fillin[] her classmates is going to visit the museum.

\begin{oneparchoices}
\correctchoice /;as well as
\choice Not only; but also
\choice Both; and
\choice Neither; nor
\end{oneparchoices}

*** Choose the best answer 22
If Mike is \fillin[], he will go to school tomorrow.

\begin{oneparchoices}
\choice good enough
\correctchoice well enough
\choice enough good
\choice enough well
\end{oneparchoices}

*** A.Complete the sentences with the given words in their proper forms 3
I managed to work for two hours without \fillin[interruption]. (interrupt)

*** A.Complete the sentences with the given words in their proper forms 10
She was \fillin[hit] by a falling vase from the building. (hit)

*** A.Complete the sentences with the given words in their proper forms 19
We \fillin[have exchanged] our ideas with each other during the meeting yesterday. (change)

** 期中复习卷二
*** A. Choose the best answer 16                                  :no_answer:
There Jack found a map on the wall, \fillin[] ?

\begin{oneparchoices}
\choice wasn‘t there
\choice didn’t there
\choice didn’t he
\choice wasn’t he
\end{oneparchoices}

*** A. Choose the best answer 19                                  :no_answer:
The student wrote a book report that was \fillin.

\begin{oneparchoices}
\choice ten-page-long
\choice ten pages long
\choice ten-pages-long
\choice ten-page long
\end{oneparchoices}

*** A. Rewrite the following sentences as required 2
A protractor is used for measuring angles. (就划线部分提问) \\
What is protractor \fillin[used] \fillin[doing]?  \\
What is protractor \fillin[used] \fillin[to] \fillin[do]?

*** A. Rewrite the following sentences as required 4
As I don’t know his address I couldn’t find him easily. (保持原意) \\
\fillin[Without] \fillin[knowing] has address, I couldn’t find him easily.

*** A. Rewrite the following sentences as required 5
John runs fastest in his class. (保持原意) \\
John runs \fillin[faster] than \fillin[the] \fillin[other] students in his class. \\
\fillin[Nobody] \fillin[else] runs as \fillin[fast] as John in his class.

*** A. Rewrite the following sentences as required 6
In order to make himself heard, the man at the door shouted as loudly as possible.(保持原意) \\
In order to make himself heard, the man at the door shouted \fillin[at] the \fillin[top] of his voice.

*** A. Rewrite the following sentences as required 9
He’s already used to the county life.(改为反义疑问句) \\
\fillin[He has used to the country life, hasn't he?][5cm]

*** A. Rewrite the following sentences as required 15
He told me that he would come back soon.(改被动) \\
\fillin[I was told that he would come back soon.][10cm]

*** A. Rewrite the following sentences as required 16
You can find a lot of differences between the two languages.(改被动) \\
\fillin[A lot of differences between the two languages can found by you][10cm].

*** A. Rewrite the following sentences as required 17             :no_answer:
Do you water your flowers every day?(改被动) \\
\fillin[Are the flowers watered every day by you?][10cm].

*** A. Rewrite the following sentences as required 20             :no_answer:
Mother was not mending the trousers.(改被动) \\
\fillin[The trousers aren't mented by mother.][10cm]

* 周拓
** 8A 英语周末拓展(一)
*** Translation 1
n. 挑战 艰巨任务 \fillin[challenge]

*** Translation 7
adj. 有益的 \fillin[beneficial]

*** Translation 8
adj. 有影响力的 \fillin[influential] (influence n.)

*** Translation 13
adj. 偶然的 意外的 \fillin[accidental]

*** Translation 15
v. 壮大 \fillin[enrich]

*** Translation 19
v. 回应 \fillin[Respond]

*** Translation 21                                                :no_answer:
Many foreigners consider Spaniards lazy. Few of them know that people there \fillin[place value on] (很重视) family time.
*** Translation 23                                                :no_answer:
直到20世纪50年代冰箱才开始流行起来。 \\
\fillin[][5cm]

*** Choose the best answer 1
Which of the following underlined parts is different in pronunciation from others?

\begin{choices}
\correctchoice We need some water to keep healthy.
\choice There is a special watch on the floor.
\choice I want to get there by underground.
\choice Don't wash the clothes in hot water.
\end{choices}

*** Choose the best answer 14
The round cake \fillin the moon is called a moon cake.

\begin{oneparchoices}
\correctchoice like
\choice is like
\choice likes
\choice looks like
\end{oneparchoices}

*** Choose the best answer 16
No one but his parents \fillin how naughty he is.

\begin{oneparchoices}
\choice know
\correctchoice knows
\choice are knowing
\choice knew
\end{oneparchoices}

*** Choose the best answer 17                                     :no_answer:
Only then \fillin that he didn't know English at all.

\begin{oneparchoices}
\fillin I realized
\fillin I did realize
\fillin did I realize
\fillin realize I
\end{oneparchoices}

*** Complete the sentences with the given words 3
Yesterday Mr.Green \fillin[was told] (tell)that the sales meeting \fillin[would be held] (hold) in the following week.

*** Complete the sentences with the given words 4                 :no_answer:
The police have issued the \fillin[] of the criminals. (describe)

*** Complete the sentences with the given words 6
Many elderly people live in \fillin[poverty] (poor)

*** Complete the sentences with the given words 7                 :no_answer:
Can you express your idea in a rather clear way without any \fillin[]? (repeat)

*** Complete the sentences with the given words 9
There are some \fillin[simibrities] between the two plays.(similar)

*** Complete the sentences with the given words 10
Can you give me a(n) \fillin[explation] for this? (explain)

*** Complete the sentences with the given words 11
If you \fillin[simplify] that story, the little boy will be sure to understand it.(simple)

*** Complete the sentences with the given words 13                :no_answer:
I noticed with great \fillin[] that you made great progress.(satisfied)

*** Rewrite the following sentences 3                             :no_answer:
The building was owned by a local businessman.(保持句意基本不变） \\
The building \fillin[] \fillin[] a local businessman.

*** Rewrite the following sentences 4                             :no_answer:
You like playing basketball, and he likes running, \fillin[] (改为反义疑问句)

*** Rewrite the following sentences 5
All of us know something about the traditional skill of cormorant fishing. (改为否定句) \\
\fillin[None] \fillin[of] \fillin[us] \fillin[knows] \fillin[anything] about the traditional skill of cornorant fishing.

*** Rewrite the following sentences 6
He doesn't watch TV every day,I think. (合并为复合句) \\
\fillin[I don't think that he watches TV][6cm]

*** Rewrite the following sentences 10                            :no_answer:
You mustn't get off the bus. It doesn't completely stop.(合并为一句）
You mustn't get off the bus \fillin[untill it stop].

** 8A 英语周末拓展(二)
*** Vocabulary 2
职业运动员 n. \fillin[athlete]
*** Vocabulary 4
隔离；孤立 n. \fillin[isolation]
*** Vocabulary 7                                                  :no_answer:
运输 n. \fillin[]
*** Vocabulary 9                                                  :no_answer:
申请人 n. \fillin[]
*** Vocabulary 15                                                 :no_answer:
The price of an island \fillin[depend] on several foctory.
They include how much the island will be developed and for what \fillin[purpose]
*** Vocabulary 16
这个故事不仅以推动情节慢慢前进的方式而且以让观众能够逐步发现真相的方式讲述。
\begin{solutionorlines}[.5in]
The way it tell the story not only puhu the plot slowly forward, 
but also enables the audience to find out the truth step by step.
\end{solutionorlines}
*** Vocabulary 17
除此以外，我特别喜欢这部电影的开放式结局。它留给观众写作的空间。
\begin{solutionorlines}[.5in]
In addition, I particularly like the film's open ending, it leaves some places for audience to fill in.
\end{solutionorlines}
*** Vocabulary 18
肯定的是，我们没有超能力去拯救世界，但是我们仍然被五个美少女战士的故事所鼓舞，并且将爱和正义留于我们的心中。
\begin{solutionorlines}[.5in]
For sure, we don't have super power to save the world, 
but we can stlll be inspired by the stroy of fine soldier and keep love and justice ih our heart.
\end{solutionorlines}
*** Choose the best answer 3                                      :no_answer:
I have just watched a good film about \fillin elderly fisherman in Guilin.

\begin{oneparchoices}
\choice a
\choice an
\choice the
\choice /
\end{oneparchoices}

*** Choose the best answer 5
Please retell the story \fillin your own words.

\begin{oneparchoices}
\choice on
\correctchoice in
\choice with
\choice by
\end{oneparchoices}

*** Choose the best answer 6
Working for a TV station is \fillin interesting work.

\begin{oneparchoices}
\choice a
\choice an
\choice the
\correctchoice \
\end{oneparchoices}

*** Complete the sentences with the given words 2
Please be \fillin[seated] at the table.(seat)

*** Complete the sentences with the given words 8
Please stay after the meeting. I have a few \fillin[announcement] to make.(announce)

*** Complete the sentences with the given words 9
Sometimes they hold brightly \fillin[colored] scarves when they dance. (color)

*** Complete the sentences with the given words 10
The \fillin[decorations] for the party are bright and cheery. (decorate)

*** Rewrite the folow ag sionences 3
The teacher told us to finish the project in a week. (改为被动语态) 
\begin{solutionorlines}[.25in]
We were told to finish the projet ih a wek by the teacher.
\end{solutionorlines}

** 8A 英语周末拓展(三)
*** SSP 1
场面，场景 n. \fillin[sense]
*** SSP 2
(社会）运动 n. \fillin[campaign]
*** SSP 4
个人的 adj. \fillin[individual]
*** SSP 6
目的地 n. \fillin[destination]
*** SSP 10
著名的 adj. \fillin[celebrated]
*** SSP 11
有影响力的 adj. \fillin[influential]

*** Vocabulary 3
In addition, pårents often have a strong \fillin[sense  of dignity] (尊严感).

*** Choose the best answers 5
-- John, there is \fillin Mr.Wilson on the phone for you. \\
-- I'm in \fillin bath.

\begin{oneparchoices}
\choice a; the
\choice the; a
\correctchoice a; /
\choice the; /
\end{oneparchoices}

*** Choose the best answers 8
There is a flower shop on \fillin side of the street. Let's go and buy some flowers.

\begin{oneparchoices}
\choice another
\choice other
\choice others
\correctchoice the other 
\end{oneparchoices}

*** Choose the best answers 11
You never imagine whát great trouble I have \fillin this paper in my house.

\begin{oneparchoices}
\choice for finding
\choice to find
\choice found
\correctchoice finding
\end{oneparchoices}

*** Choose the best answers 15
The monkey was hanging \fillin the tree \fillin his tail and laughing.

\begin{oneparchoices}
\choice on, by
\choice to, as
\choice above, by
\correctchoice from, by
\end{oneparchoices}

*** Choose the best answers 20
He \fillin a dollar bill in the suit he was sending to the cleaner's.

\begin{oneparchoices}
\choice came to
\choice came out
\correctchoice came across
\choice came up
\end{oneparchoices}

*** Fill in the blanks according to the given words 1
On the Double \fillin[Ninth] Festival, people usually climb mountains. (nine)

*** Fill in the blanks according to the given words 5
Let Tom tell you the truth \fillin[straight]. (straight)

*** Fill in the blanks according to the given words 6             :no_answer:
\fillin[] by the results, the child returned home in silence. (courage)

*** Fill in the blanks according to the given words 8
The mountain climbers were lost in the snow and nearly \fillin[freeze] to death. (freeze)

*** Fill in the blanks according to the given words 10            :no_answer:
If we as \fillin[] don't change our behavior, more disasters will come.(human)

*** Rewrite the following sentences as required 7
I won't go to Kate's birthday party if she doesn't invite me. (保持句意不变) \\
I won't go to Kate's birthday party \fillin[unless] she \fillin[invites] me.

*** Rewrite the following sentences as required 8                 :no_answer:
Nobody knew what had happened, \fillin[] \fillin[they]? (反意疑问句)

*** Rewrite the following sentences as required 9
He is a good basketball player.(感叹) \fillin[How] \fillin[well] he plays basketball!

* 平时
** 8A Exercise for U5
*** Dictation 6
v. 达到 \fillin[achieve]

*** Dictation 10
n. 小偷 \fillin[thief]

*** Dictation 12
adj. 正确无误的 \fillin[correct]

*** Dictation 13
n. 闪电 \fillin[lightning]

*** Choose the best answer 10                                     :no_answer:
Her cousin can draw \fillin an artist.

\begin{oneparchoices}
\choice not as good as
\choice as good as
\choice not as well as
\choice as well as
\end{oneparchoices}

*** Fill in the blanks with proper forms 6
The phone rang, while the Lis \fillin[watching](watch) TV in the sitting-room.

*** Replace words in blod 2
It is *a drawing or film of drawings* that usually makes you laugh.
Replace words in blod: \fillin[cartoon]

*** Replace words in blod 8                                       :no_answer:
The rice wine was kept in huge *containers for holding food or drink* .  \\
Replace words in blod: \fillin[]

*** Replace words in blod 9                                       :no_answer:
Tommy looked through the *letters, parcel sent by post* to see if there were any letters for him.  \\
Replace words in blod: \fillin[]

*** Replace words in blod 10
Tommy is so *thin* that he *looks like as* \fillin[Skeleton].

*** Fill in the blanks with proper prepositions 2                 :no_answer:
Guangzhou is famous \fillin[] its beautiful views along the Pearl River. (珠江)

*** Fill in the blanks with proper prepositions 5                 :no_answer:
Can you write this sentence \fillin[] three languages?

*** Fill in the blanks with proper prepositions 6                 :no_answer:
Ancient Egyptian was not a language \fillin[with] letters and words \fillin[] English.

*** Fill in the blanks with proper prepositions 10
Look \fillin[at] the pictures \fillin[on] the next page.

*** Fill in the blanks with proper prepositions 11                :no_answer:
\fillin[] most other students, Tom is very clever.

*** Fill in the blanks with proper prepositions 12                :no_answer:
We knew \fillin[about] the facts \fillin[] an encyclopaedia.

*** Fill in the blanks with proper prepositions 14
They were drinking beer \fillin[with]  big bottles.

*** Fill in the blanks with proper prepositions 15
She is listening to a travel programme about Nanjing \fillin[on] the radio.

*** Fill in the blanks with proper prepositions 18                :no_answer:
It is over 160 hectares \fillin[] size.

** 8A Exercise for U6
*** Vocabulary 1
描写 v. \fillin[describe] -- n. \fillin[description]

*** Vocabulary 4
存在 n. \fillin[existence]

*** Choose the best answer 2
At last he taught Peter a lesson \fillin a trick.

\begin{oneparchoices}
\choice in
\choice for
\correctchoice by
\choice with
\end{oneparchoices}

*** Choose the best answer 9
The little boy put the ladder \fillin the wall and left.

\begin{oneparchoices}
\choice at
\choice on
\choice off
\correctchoice against
\end{oneparchoices}

*** Choose the best answer 13
Are you going to \fillin us \fillin the lecture \fillin the Chinese culture?

\begin{oneparchoices}
\choice attend, in, of
\correctchoice join, in, on
\choice take part in, at, about
\choice join, at, of
\end{oneparchoices}

*** Choose the best answer 18
\fillin trees is becoming smaller and smaller.

\begin{oneparchoices}
\choice A number of
\choice Many
\correctchoice The number of
\choice Some
\end{oneparchoices}

*** Choose the best answer 21
The film "War of the Worlds" has \fillin for a week.

\begin{oneparchoices}
\correctchoice been over
\choice finished
\choice ended
\choice been off
\end{oneparchoices}

*** Choose the best answer 22                                     :no_answer:
My car \fillin

\begin{oneparchoices}
\choice needs to fepair
\choice need repair
\choice needs repairing
\choice needs repair
\end{oneparchoices}

*** Choose the best answer 27                                     :no_answer:
He asked me \fillin

\begin{oneparchoices}
\choice where did Tom spend his last holiday
\choice that he was going to buy a new bicycle
\choice why he had given them such a lecture
\choice if I have a lovely time at Christmas
\end{oneparchoices}

*** Choose the best answer 29                                     :no_answer:
Would you like to give us an introduction \fillin the film?

\begin{oneparchoices}
\choice to
\choice for
\choice of
\choice in
\end{oneparchoices}

*** Choose the best answer 33                                     :no_answer:
Jim sat \fillin to his mother with his eyes half \fillin .

\begin{oneparchoices}
\choice closed; opened
\choice close; open
\choice closely; opening
\choice close; opened
\end{oneparchoices}

*** Complete the sentences with the given words in their propertors 2
The n\fillin[avigator] (person who finds the way on the plane) 
looked at the map and told the pilot which direction to go for the airplane.

*** Complete the sentences with the given words in their propertors 6
My offce is on the 11th floor of a building with 18 s\fillin[toreys] (levels of a building)

*** Complete the sentences with the given words in their propertors 9
We s\fillin[prang](rose up quickly) to our feet when the master entered the room.

** 8A Exercise for U7
*** Vocabulary 15
有益的 adj. \fillin[beneficial]

*** Vocabulary 16
有影响力的 \fillin[influential]

*** Vocabulary 17
存在 n. \fillin[existence]

*** Vocabulary 18
不可思议的 adj. \fillin[incredible]

*** Choose the best answers 2
John plays basketball \fillin , if not better than Jim.

\begin{oneparchoices}
\choice as well
\choice so well as
\choice so well
\correctchoice as well as
\end{oneparchoices}

*** Choose the best answers 5
Professor Liu gave us a very useful \fillin on how to prepare for the exam.

\begin{oneparchoices}
\choice advice
\choice experience
\choice information
\correctchoice suggestion
\end{oneparchoices}

*** Choose the best answers 8
If you \fillin water, it \fillin steam.

\begin{oneparchoices}
\choice boil,will become
\choice boil,become
\choice will boil,will become
\correctchoice boil,becomes
\end{oneparchoices}

*** Choose the best answers 14
The old man was too weak and \fillin down on the bed.

\begin{oneparchoices}
\choice lied
\correctchoice lay
\choice lain
\choice laid
\end{oneparchoices}

*** Complete the.sentences with the proper words 12
Many things left by the ancient \fillin[Egyptians] in tombs have been brought to light. (Egypt)

*** Complete the.sentences with the proper words 13
Early diagnosis(诊断） and treatment can prevent \fillin[blindness] (blind)

*** Rewrite the sentences 8
His handwriting is the best in the class.(保持句意不变）
His handwriting is \fillin[better] than anyone \fillin[else's] in the class.

** 8A 语法训练1
*** A. Choose the best answer 10
They wanted to know whether they \fillin a rehearsal(排演) before performing on stage.

\begin{oneparchoices}
\choice will have
\choice had
\correctchoice would have
\choice have had
\end{oneparchoices}

*** A. Rewrite the sentence ad required 1
My husband has never sent flowers to his mother on Mother's Day.(改为一般疑问句)\\
\fillin[Has your husband ever sent flowers] to his mother on Mother's Day?

*** A. Rewrite the sentence ad required 3
John denied cheating in the English test.(改为反义疑问句)\\
John denied cheating in the English test, \fillin[didn't he]?

*** B. Choose the best answer 1
Which of the following underlined parts is different in pronunciation from the others?

\begin{oneparchoices}
\choice small
\choice talk
\choice chalk
\correctchoice salt
\end{oneparchoices}

*** B. Choose the best answer 3
The manager is very busy and always calls his client \fillin[] .

\begin{oneparchoices}
\choice On his way to home
\choice his way home
\choice on her way home
\correctchoice on the way home
\end{oneparchoices}

*** B. Choose the best answer 5
We try our best to make our country \fillin in the world.

\begin{oneparchoices}
\choice More beautiful
\choice more beautifully
\choice more beauty
\correctchoice the most beautiful
\end{oneparchoices}

*** B. Choose the best answer 6                                   :no_answer:
Mr. Black \fillin to the cinema last Sunday because he \fillin the film.

\begin{oneparchoices}
\choice Hasn’t gone; has seen
\choice didn’t go; has seen
\choice didn’t go; has seen
\choice hasn’t gone; had seen
\end{oneparchoices}

*** B. Choose the best answer 11
It is \fillin of the girl to say no to the computer game.

\begin{oneparchoices}
\choice sensitive
\choice honest
\choice kind
\correctchoice sensible
\end{oneparchoices}

*** B. Choose the best answer 12
The students were talking happily when suddenly the alarm \fillin[].

\begin{oneparchoices}
\choice Went out
\choice went in
\choice went up
\choice went off
\end{oneparchoices}

*** B. Fill in the blank with a proper word 2
We've made \fillin[unbelievable] progress, and hopefully we can continue that. (believe)

** 8A 语法训练2
*** A. Choose the best answer 7
My uncle \fillin[] as a manager since he came back from the USA five years ago.

\begin{oneparchoices}
\choice Worked
\correctchoice has worked
\choice works
\choice had worked
\end{oneparchoices}

*** A. Fill in the blank with a proper word 3
The parents often have \fillin[arguments] about the education of their children. (argue)

*** A. Fill in the blank with a proper word 7                     :no_answer:
If you don't listen to the teacher \fillin[] , you are likely to miss some important points.(attention)

*** A.Rewrite the sentence as required 2
My father bought me a new computer.(改为被动语态) \\
A new computer \fillin[was broght for me by my father.][10cm].

*** A.Rewrite the sentence as required 6                          :no_answer:
annoying,always,buy,asks,unnecessary,me,something,salesman,the,to,(连词成句) \\
\fillin[][12cm]

*** B. Choose the best answer 3
Betty used to \fillin[] to school, but now she \fillin[] to school by bus on weekdays.

\begin{oneparchoices}
\choice walking,goes
\choice walking, is going
\correctchoice walk,goes
\choice walk,is going
\end{oneparchoices}

*** B. Choose the best answer 6
Learning \fillin[] country's language is a better way of knowing \fillin[] culture behind it.

\begin{oneparchoices}
\choice the,a
\choice a,the
\choice /,the
\choice a,/
\end{oneparchoices}

*** B. Fill in the blank with a proper word. 3
Betty's \fillin[success] in winning the gold medal made all of us proud of her.(successful)

*** B. Rewrite the sentences as required. 2
The bookshelf is so high that the boy can't reach the top of it.(保持原句意思) \\
The bookshelf isn't \fillin[low enough for the boy to][5cm] reach the top.

*** B. Rewrite the sentences as required. 5
The headmaster wrote an email to the students who won the top prize in the contest.(改被动语态) \\
The students who won the top prize \fillin[were written an email to][5cm] by headmaster in the contest.

*** C.Choices 4
It is \fillin to send a letter by air mail than by ordinary mail.

\begin{oneparchoices}
\choice much quickly
\correctchoice much quicker
\choice more quickly
\choice more quicker
\end{oneparchoices}

*** C.Choices 7                                                   :no_answer:
The prices of the film tickets nowadays are far \fillin . Some of the citizens can't afford them.

\begin{oneparchoices}
\correctchoice more expensive
\choice cheaper
\choice higher
\choice expensive
\end{oneparchoices}

*** C.Choices 14
Jim \fillin to answer the questions that was \fillin by the teachers.

\begin{oneparchoices}
\correctchoice rose / raised
\choice raised / rise
\choice rose /risen
\choice raised /raised
\end{oneparchoices}

*** C.Choices 20
\fillin of us knows that Jack Ma is the founder of Alibaba.

\begin{oneparchoices}
\choice All
\correctchoice Every one
\choice Everyone
\choice both
\end{oneparchoices}

** Good beginning is half done
*** 选用(success 的相关词)
选用(success 的相关词)
My ambition is to become a \fillin[successful] man. 
Therefore, I try hard to have \fillin[success] in getting the prizes in various contests.
Now my efforts \fillin[successed]. 
I'm very proud of it. I can tell everybody I have done it \fillin[sccestully].
*** Newspaper feedback 1
v. 提议；打算 \fillin[propose]
*** Newspaper feedback 5
v. 延伸 \fillin[extend]
*** TODO Newspaper feedbactk 18
他们不习惯寻找户外的娱乐活动，也没有培养创造地娱乐自己的能力。
\fillin[The don't get ability to looking for outdoor entertainment][2in].
*** Choose the best answer 7
Today newly-produced mobile phones which can take photos \fillin a camera is famous \fillin its powerful function.

\begin{oneparchoices}
\choice as, for
\choice as, as
\correctchoice like for
\choice like, as
\end{oneparchoices}

*** Choose the best answer 10
Daisy is a student who is always strict \fillin her study.

\begin{oneparchoices}
\choice with
\choice to
\choice for
\correctchoice in
\end{oneparchoices}

*** Rewrite the following setence 4
"John, will you go abroad to continue your study next year?" Susan asked.(改宾从句)
\fillin[]



